### ISSUE TITLE
Would you recommend using Kopia in a professional setup ?

### ISSUE THREAD

**Issue by jpbourgeon** [kopia/kopia#1007]
Hi,

I couldn't find any reference of Kopia usage in a professionnal setup.

Would you recommend using it in a medium enterprise environment as the main backup software for : 

- A global active volume of 8TB
- A granular backup of the fileserver for quick restoration
- A backup of the virtual machines snapshots

Do you have examples, testimonials of this kind of usage,

Regards,

--
Jean-Philippe

**Comment by ZoomRmc** [comment]
There's no such thing as "the main" backup software. If the data is valuable, there should be at least 2 solutions working independently in parallel. *Especially* in case when backup process entails some data transformation (converting to blocks in a specialized repository), and not just straight copying.

My SOHO experience is at this point very limited, but I'm in the process of replacing one of the backup solutions I consider second-tier with Kopia. Total data set is just ~ 2TB, mostly media. The most critical part - recovery - wasn't tested sufficiently yet (haven't tried restoring a whole repo).

**Comment by jkowalski** [comment]
I second that. I personally have been using Kopia as my primary backup mechanism for ~2 years now (although it was a very different tool 2 years ago) but I have secondary backup of my most important stuff elsewhere. In general 3-2-1 backup strategy is a good one - have 3 copies, two different media, 1 offsite.

I think all the scenarios you mention are within scope of Kopia and are being regularly used by the community members.

**Comment by bbccdd** [comment]
You could use kopia as the main backup as long as you also have a secondary backup system. In fact, the rolling hash feature and deduplication work great on large files that change a bit but not completely every time (e.g. VM's).

I'm using Kopia as a secondary backup system since it is absolutely superbly engineered. It has huge potential to do everything I ever wanted from backup tooling (compared borg backup, restic, duplicati (current main solution), duplicacy, dup, bareos, bacula, UrBackup, BackupPC, DirSync Pro, Box Backup, Areca Backup, Proxmox Backup and Arq. 

The rclone backend for kopia is a simple and fantastic add-on you could use to store your data end-to-end encrypted on yet another cloud storage provider (reaching a 4-3-2 scheme ;). It is widely used by academic research institutes such as CERN. For storage you can get that cheap or simple cheap e.g. Microsoft 365 family offers 6 users x 1TB for EUR 60 or so per year at a discount reseller. With a bit of compression (tip: run 'kopia benchmark compression' before you create your repositories) that could suit your needs. Or use the ultra cheap backblaze for EUR/GB/month (but mind the hidden cost of class C-transactions), so test for a while. 

Kopia is very actively developed and highly advanced (not just technically, also in terms of API/end-user documentation) yet young. 

If you have bandwidth to spare you could have hourly snapshots (that only take a hand full of seconds to make) of all your data next to whatever you are using now. Just don't put all your bits in one basket.

**Comment by jpbourgeon** [comment]
Thank you all for your positive feedback and advice.
I'll take that into account while crafting our backup strategy.

**Comment by julio-lopez** [comment]
As a data point, Kasten's K10 product uses Kopia extensively to backup application data for applications running on Kubernetes.
