### ISSUE TITLE
Using mount with "all" option in Windows mounts the source directories instead of the snapshots

### ISSUE THREAD

**Issue by xbb** [kopia/kopia#1050]
As subject I noticed I could change/write/delete files when mounting with the all option

The changes persisted between remounts but they were not showing in the snapshots when mounted individually

I noticed later that it was actually mounting the source directories and I was changing those via the webdav mount

**Comment by bbccdd** [comment]
Hi @xbb is your finding similar to my issue #1044 by any chance? It looks similar from where I'm standing.

**Comment by alphaleonis** [comment]
From what I could see, it actually does mount the correct directories, the problem is that navigating there is not possible in Windows since the path contains the drive letter.  In my case for example, it mounted `Z:\user@host\D:\Documents`. However no windows program I found could navigate into this. In command line and explorer if you navigate down there you actually end up in `D:\Documents`, i.e. the source directory.  So perhaps just using something other than the `:` character to denote the drive would solve this.

**Comment by xbb** [comment]
You are right, just tested this.

Also `\` is forbidden as per https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

**Comment by alphaleonis** [comment]
Well, `\` is a directory separator, so replacing the `:` with a `\` (or rather just removing the `:`) in this case probably would work quite nicely I think. (Would make the drive letter a normal directory)
