### ISSUE TITLE
docker with UI

### ISSUE THREAD

**Issue by mariomare22** [kopia/kopia#1055]
Hello, I did not find any reference for the docker container with a webUI.

Is this something in scope? if it's available, how to implement it?

Thanks

**Comment by xbb** [comment]
I haven't tried myself but start by taking a look at the `kopia.exe server --help-full` command.

Docker images are already available:
https://kopia.io/docs/installation/#docker-images

**Comment by xbb** [comment]
I quickly tested it and got the UI running with this run command:

```
docker run \
    -p 51515:51515 \
    -e KOPIA_PASSWORD=password \
    kopia/kopia server \
        --address=http://0.0.0.0:51515 \
        --insecure \
        --ui \
        --server-username=admin \
        --server-password=admin
```

Modify the command as appropriate and map the required volumes, also you should use an env-file for the password, server username and password, etc instead of the command flags

On your clients use `--override-hostname` and `--override-username` as documented in the installation docs
