### ISSUE TITLE
KopiaUI creates pop-up windows for every repo on startup

### ISSUE THREAD

**Issue by milliontown** [kopia/kopia#1314]
Kopia version: 0.9.0-rc2
OS version: Windows 10 21H1 19043.1165

After auto-updating, KopiaUI opens a new window for every repo on every login. This is new behavior and not something I expect is intended. Attached is a screenshot of the experience with the taskbar right-click menu shown. The `<not connected>` repos are two external drives that I only connect once a month and the third is the default non-configurable repo (I think?).

![090rc2_startup](https://user-images.githubusercontent.com/91389846/134783569-8a0f37c4-2a4e-4176-8931-b2fb476c0a92.png)

**Comment by xxxliqu1dxxx** [comment]
That always happens for me and has been in previous versions as well. 

If the repos are reachable then they auto connect and do not show this window. If the repos are not reachable then this shows as blank and allows to resupply the connection information to reach the actual repo. 

In your use case you use external drives so that would explain why this blank window shows up if your external drive is not plugged in when you opened the UI. 

Unless I a missing something there’s no problem here.

**Comment by milliontown** [comment]
Interesting that you have always had this. But like I said, there's actually four windows - one for every repo - stacked on top of each other. Even the reachable repo pops up.

**Comment by tmoehlman** [comment]
Is there any way to not have the windows popup on startup (ie minimize to tray only)?   Also, is there any way to get rid of a <not connected> if it isn't used?

**Comment by VsevolodGolovanov** [comment]
Happens on each startup for me too. That's not a popup window though, just a normal window.

**Comment by LakeishaKowalczyk** [comment]
+1
It's a little annoying
