### ISSUE TITLE
New fresh repo on OneDrive, using rclone backend and this shows up...

### ISSUE THREAD

**Issue by xxxliqu1dxxx** [kopia/kopia#1350]
New fresh repo on OneDrive, using rclone backend and this shows up after my first snapshot:

![image](https://user-images.githubusercontent.com/83290244/135768419-4a94e787-0885-465a-8108-5f85f6767495.png)

Following the prompts I see this:
![image](https://user-images.githubusercontent.com/83290244/135768630-fa70fc9e-ad47-4c6e-bd36-53520e572c69.png)

And then as expected, this shows "as normal"... all kopia files:
![image](https://user-images.githubusercontent.com/83290244/135768658-a3a5e75a-040c-44b8-aa02-e16c3b23ce0d.png)

Another view with the rclone ls command
![image](https://user-images.githubusercontent.com/83290244/135768455-00cd2df8-e2a8-4b77-8602-4ebba42a77c9.png)

I uploaded stuff to OneDrive before and this never showed up. I am not sure if this is new to OneDrive or caused by RC3. As mentioned these are "new OneDrive accounts" which are "Fresh", empty... so perhaps that's the issue, but maybe someone here knows what's wrong.

I am sure this is a false positive as like I said the only stuff on there are kopia files, but I wonder if perhaps OneDrive triggers that ransomware stuff due to the way files are named with Kopia... is there a way to change the filenames or directory structure to avoid this situation? I know there's a --flat parameter which I tried, and this did not seem to do anything for me...

In any case, I will continue to play with this, but I found it interesting that it triggered this false positive. 

Thanks in advance if you can provide an answer :)

**Comment by xxxliqu1dxxx** [comment]
If I create the repo within an rclone crypt, this does not seem to trigger that OneDrive "protection"... so I will use that workaround for now.

**Comment by zyradyl** [comment]
out of curiosity, when you use rclone crypt what do the files in OneDrive look like?

it seems like this is [intended behavior](https://support.microsoft.com/en-us/office/ransomware-detection-and-recovering-your-files-0d90ec50-6bfd-40f4-acc7-b8c12c73637f) at least on OneDrive's end. in particular, the .f file extension would be "strange" to 365, so it gets flagged.

i tried looking for more information on the specifics of the detection, but all i can find is references to mass-deletions, or strange filenames and extensions.

**Comment by xxxliqu1dxxx** [comment]
> 
> 
> out of curiosity, when you use rclone crypt what do the files in OneDrive look like?
> 

Rclone crypt changes all filenames and directories to alphanumerical. Here's the root folder:
![image](https://user-images.githubusercontent.com/83290244/136061265-8a25c861-4927-419e-9594-2434d05892d1.png)

and subfolder:

![image](https://user-images.githubusercontent.com/83290244/136061322-9b493dce-dc6d-4c1e-9765-d9ca8293d3bc.png)

@jkowalski  is there a special reason the files are named with .f if that's what triggers the OneDrive ransomware protection? I do not really need the "double encryption", the one kopia offers may be good enough, although I understand rclone's crypt on top of the kopia one would make things pretty secure I guess... I think I'd rather just have kopia put files directly on the cloud for simplicity.

**Comment by zyradyl** [comment]
i dug into the code a bit to see what i could figure out, here are some of my notes:

-  `rclone`, `webdav`, `sftp`, and `filesystem` all use the [`sharded.go`](https://github.com/kopia/kopia/blob/master/repo/blob/sharded/sharded.go) repository layout, which per the [docs](https://kopia.io/docs/getting-started/#filesystem) is done to optimize performance. if i had to guess, the goal is to reduce the total number of potential files in each folder, which isn't a problem on object storage providers.
- the full path to the sharded `blob` (so stringing all directory names together and the filename) gives the filename that would be used on object storage, the difference being the suffix.
- the suffix is used to denote that a blob is "complete"
- a function called `HasSuffix` is used to only process blobs that are completed under `getBlobIDFromFileName`. this is actually used in a few other places too, like [`command_blobs_shards_modify.go`](https://github.com/kopia/kopia/blob/master/cli/command_blob_shards_modify.go)

it's possible that it could be switched over so that temporary files have an extension and finalized ones do not? it doesn't seem intuitive to do though. i'm trying to learn a bit more about how Kopia functions though, so i'll fiddle a bit. my concern would be that we do all this and it still triggers because of the filename 😅

i don't use OneDrive, if i put together an unofficial binary would you be willing to test it?

**Comment by xxxliqu1dxxx** [comment]
@jkowalski  I am pretty sure OneDrive offers free storage and perhaps does not require the referral, but please let me know how I can assist as I can "Refer" you so you get free storage for testing purposes.

**Comment by xxxliqu1dxxx** [comment]
> i don't use OneDrive, if i put together an unofficial binary would you be willing to test it?

Hi [zyradyl](https://github.com/zyradyl), sorry I just noticed this today, but yes I am willing to test things out... I really want to use Kopia with OneDrive but this false positive ransomware detection is really not great. Please let me know how I can test this.

**Comment by xxxliqu1dxxx** [comment]
Alternatively @jkowalski  would you be able to confirm if a feature to alter the filename file extensions and prevent this false positive ransomware detection is on the roadmap? I look forward to this working. Thanks!
