### ISSUE TITLE
Kopia documentation missing?

### ISSUE THREAD

**Issue by petersjostrom** [kopia/kopia#1440]
https://kopia.io/docs/reference/command-line/common/
This page has no sub-pages about "kopia snapshot...", but there are pages if you search, like "snapshot create", "snapshot list", etc.
Seems the documentation lists only the first X sub-pages, the rest are not indexed and visible?
I can't find any info on snapshot commands on the documentation or site either.

**Comment by CrendKing** [comment]
There is a script that goes through all CLI commands in source and generate a doc page for each. There are currently 80 "common commands". However, the source code for the sidebar is hardcoded to [only display the first 50](https://github.com/kopia/kopia/blob/2394b420b02eaf301b3eb4e0f0626cd124f60469/site/themes/docsy/layouts/partials/sidebar-tree.html#L32). And since "`s`napshot" arrives late in the alphabet, they are truncated.

The fix would be easy. Just raise the number. But then the sidebar may become too long. I wonder maybe a better solution would be not listing commands in sidebar, but in a generated page, which provides links to each command's page. This way the page is OK to be long and exhaustive. This does require some rewriting though.

Does hugo allow a page to exist without being listed?

**Comment by CrendKing** [comment]
Attempt to fix the doc: https://github.com/kopia/kopia/pull/1525
