### ISSUE TITLE
Expose the notion of "free space" in blob.Storage

### ISSUE THREAD

**Issue by jkowalski** [kopia/kopia#1520]
For storage systems where free space is limited (basically filesystem and other non-cloud), it is important to prevent filling up the underlying disk, which can result in the repository becoming hard to recover (since deleting snapshots requires temporarily using more disk space for tombstones)

Assuming we implement something like #1519, we can have a condition that prevents new snapshots from being taken if the free space in the repository drops below certain level.

**Comment by keesse** [comment]
My experience with a full backup volume with `kopia`:
I was using 0.7.3 if I remember correctly, during a snapshot, the USB disk happened to get filled 100%.
The repository seemed defective.
When making room by removing my old restic repository, kopia managed to heal the repository and no snapshott was lost!  
So @jkowalski , a very solid piece of software!!!

**Comment by adowair** [comment]
# Design Proposal
Hey folks, here's a little writeup of a design for this feature. Any feedback and inputs are appreciated.
## API Changes
We can expand the repo `blob.Storage` interface to include a `GetCapacity()` template:
```go
type Storage interface {
	Reader
	PutBlob(ctx context.Context, blobID ID, data Bytes, opts PutOptions) error
	DeleteBlob(ctx context.Context, blobID ID) error
	Close(ctx context.Context) error
	FlushCaches(ctx context.Context) error

        // GetCapacity returns how much free, usable capacity this backing store has.
       GetCapacity(ctx context.Context) /* <return_type> */
}
```
Where `return_type` needs to be flexible enough for two scenarios:
- When the backing store has limited storage, be a sensible representation of how much space there is
- When the backing store has practically unlimited storage, indicate that in a reasonable way, so that any other code that relies on this interface can make sense of it.

I propose a composite type:
  ```
  type Capacity struct {
    limited bool
    size uint64
    free uint64
  }
  ```
where if `limited` is set to `True`, the two int variables are populated and used. Otherwise, they are ignored (default to zero). We can use this interface like so (example for #1519):
```go
if c = s.GetCapacity(ctx); c.limited {
  if c.size - c.free < /* some requirement */ {
    return errors.New("Not enough space on storage to take snapshot") 
  }
}
s.DoTakeSnapshotThings() // pseudocode
```

An alternative is to split this information between two functions: `IsSpaceLimited()` and `GetFreeSpace()`. One or both of these functions can be called as needed. This rids of us the need for the `Capacity` struct as well.
