### ISSUE TITLE
Request: kopia sync-to command changes exit code when it fails.

### ISSUE THREAD

**Issue by ericma15** [kopia/kopia#1586]
Hey，Now I use crond-like tools to automatically sync my repository. I'd like to see when it fails I get a email. But in fact, altough it runs fails, the exit code still is 0. So my tool think it run success and not send notification. Is there any way can we detect it run fail？

**Comment by Neurrone** [comment]
I was horrified to discover my backups have been failing for some time now because of a similar issue. My snapshot create command was failing due to this error:

> [31mERROR[0m open repository: repository is not connected. See https://kopia.io/docs/repositories/

Yet it still returns an exit code of 0, so my alerting wasn't able to notify me that something was wrong. If I hadn't checked my logs, I would never have known this was happening, so this feels like a critical bug.

**Comment by jkowalski** [comment]
I can't reproduce this error code situation:

```
kopia --config-file=no-such-file snap create .; echo "exit code: $?"
ERROR open repository: repository is not connected. See https://kopia.io/docs/repositories/
exit code: 1
```

**Comment by jkowalski** [comment]
@ericma15 can you describe the kind of failure you're getting and how you're looking at the status code? as of now I can't repro this.

**Comment by Neurrone** [comment]
My bad, I've just figured out that this problem is my own fault, I was redirecting the output of the command elsewhere, so the status code was not that of kopia. I'm wondering if OP is encountering the same thing?

**Comment by ericma15** [comment]
yes,you're right. i made the same mistakes. i'll close this issue.

**Comment by ericma15** [comment]
yes,you're right. i made the same mistakes. i'll close this issue.

**Comment by ericma15** [comment]
applogize for wrong alarm.
