### ISSUE TITLE
XChaCha20 Encryption

### ISSUE THREAD

**Issue by luboslives** [kopia/kopia#1588]
Hi, I've been doing a bit of reading and I see XChaCha20 being recommended over ChaCha20 these days. Is it plausible for Kopia? I see in the libsodium docs that it's _"currently not widely implemented outside the libsodium library, due to the absence of formal specification"_.

https://libsodium.gitbook.io/doc/advanced/stream_ciphers/xchacha20

**Comment by jkowalski** [comment]
That is possible, in fact quite easy (the library we use supports extended nonces), but since Kopia uses per-content encryption keys, any key recovery from a nonce collision would only affect one piece of content and not reveal anything about other contents:

The encryption pseudo-code in this case is:

```
# computed once:
keyDerivationSecret = hkdf(sha256, secret=perRepositoryMasterKey, size=32, salt="purposeEncryptionKey")

# hashing and encrypting content (deduplication):
contentID = keyed-hash-function(data, secret=perRepositoryHMACSecret)
IF NOT PRESENT(contentID):
  encryptionKey = hmac-sha256(contentID, secret=keyDerivationSecret)
  cipherText = chacha20poly1305.Seal(nonce=randomBytes(12), encryptionKey, plainText, info=contentID) 
  add-to-pack(cipherText )
```

Any given piece of content (`data`) is always going to be encrypted with unique `encryptionKey` that is never shared with other data. 

Nonces are random so that if two clients encrypt the same `data` at the same time and they don't deduplicate (race condition), the ciphertext will be different and won't reveal that the contents are actually the same. 

If we don't want this property, we might as well use all-zero nonce and save 12 bytes per content this way.
