### ISSUE TITLE
"~" is incorrectly parsed in directory path for new filesystem repo  

### ISSUE THREAD

**Issue by adowair** [kopia/kopia#1611]
Hello,

I ran into an issue where it seems the tilde character (`~`) is not correctly expanded/parsed when creating a new filesystem repository through the Kopia UI.

### Setup
- Kopia UI for (Intel) Mac, version  `20211220.0.0-c6415592`, build `c641559284f27bbafb9c4781a0ec183f0953d02c`
- macOS Monterey, version `12.0.1 (21A559)`

### Steps
1. Execute `mkdir ~/dev/kopia_demo_repo`
2. Launch KopiaUI
3. Under "Repository" tab, select "Filesystem"
4. Enter `~/dev/kopia_demo_repo` in Directory Path field
5. Generates the error `Connect Error: INTERNAL: internal server error: cannot access storage path: stat ~/dev/kopia_demo: no such file or directory`, even though running `stat ~/dev/kopia_demo` from the shell gives a positive result.

What gives? Could this be an effect of how paths are parsed in Kopia code? Permissions?

Thank you!

**Comment by julio-lopez** [comment]
Depending on the shell, `~` is expanded by the shell. The kopia CLI also expands `~` in some cases.

Part of the issue here is that in the UI case, on the server side it is not clear what the meaning of `~` should be. In the desktop client it should be possible to expand `~`, but it may not work when accessing the UI from a browser.
