### ISSUE TITLE
Feature Request - KopiaUI : Reschedule missed backups

### ISSUE THREAD

**Issue by jinie** [kopia/kopia#1649]
It appears KopiaUI has no option to reschedule missed backups, i.e. when used to backup from a desktop.

Expected behavior would be to run a missed backup on the "earliest chance", though if multiple backups are missed, only the latest one should be run.

**Comment by bbccdd** [comment]
Why not increase the frequency of taking snapshots? Since snapshots are light on system resources, the next backup attempt may come soon enough to provide an acceptable recovery point/time objective.

**Comment by talios** [comment]
> Since snapshots are light on system resources

They may be lite - but they may also be time consuming - at least on my docker/NAS image - my current snapshot - which is only 120gb runs for 3170.8s thru to 7252.8s, then ends up as "incomplete", I've yet to have a "complete" snapshot run successfully in one hit from the NAS ( this may be cause I'm limiting the CPU - I may increase that ), or because the files its snapshotting are part of a DB/cache/process.

Whilst not a reschedule option like @jinie wants, a retry option would be nice - maybe a "retry after NNNNs" would help.

I suppose I could increase the snapshot frequency as well - I assume Kopia won't start another snapshot if ones currently in progress?

**Comment by jinie** [comment]
> Why not increase the frequency of taking snapshots? Since snapshots are light on system resources, the next backup attempt may come soon enough to provide an acceptable recovery point/time objective.

That might also be an option. I may just me stuck in old habits, and my focus was on the desktop experience.

Personally I have no interest in "hoarding" 200 different versions of any file/document I'm working on, which is essentially what frequent snapshots would produce. That's why I backup every 4-6 hours or so, depending on the client computer.

My "normal" backup schedule is to backup at noon, and again at the end of the workday, but end of workday varies, so it doesn't always backup, which is where a "missed backup" schedule would come into play.

**Comment by sagarbehere** [comment]
:+1: Re-trying a missed backup at the next available opportunity would be really nice. My current backup tool, [Relica, has this](https://relicabackup.com/docs/backup-schedules) and it is a strong advantage for desktop/laptop systems that may be powered off or asleep at the scheduled backup time.

**Comment by Gamax42** [comment]
Upgrading from Cobian Backup to Kopia, I miss that feature, which is pretty useful for a desktop computer
