### ISSUE TITLE
actions are not run when scheduled through web ui

### ISSUE THREAD

**Issue by arminus** [kopia/kopia#1812]
With https://github.com/kopia/htmlui/pull/30 in place, I added an afterSnapshotRoot like so:
```
    "actions": {
        "afterSnapshotRoot": {
            "path": "/root/kopia_check.sh",
            "timeout": 300,
            "mode": "essential"
        }
    }
```
This script is run when I manually start the snapshot from the WebUI, but not when it is run by a schedule which is part of the same policy:
```
    "scheduling": {
        "timeOfDay": [
            {
                "hour": 3,
                "min": 0
            }
```
Kopia is started with `kopia server --enable-actions ...` and is of course running in the background.

**Comment by tribor** [comment]
There is definitely some kind of bug in the UI on defining essential actions (see also https://kopia.discourse.group/t/before-snapshot-action-mode-is-set-to-must-succeed-but-snapshot-proceeds-afterwards/1576).

I can confirm that you have to switch in the UI to 'ignore failures' (optional) and back to 'must succeed' for the essential mode to show up at 'Effective' column and thus be activated. Otherwise the 'Effective' column will be empty.
