### ISSUE TITLE
[Feature request] Setup and teardown actions

### ISSUE THREAD

**Issue by CrendKing** [kopia/kopia#1814]
I have use case where my local filesystem backup drive should be unmounted after all backup read and write operations are done (either via each CLI command or each scheduled task), and mounted before any operation happens so that Kopia can access the storage. Ideally I should put the mount/unmount command in a script and make Kopia run that in some sort of setup and teardown actions. To my knowledge, currently Kopia only has actions around individual snapshot operations, which is too late for setup and too early for teardown, and too fine-grained.

**Comment by jkowalski** [comment]
This is unfortunately infeasible - would create a chicken-and-egg problem, since snapshot times are calculated based on policies which are in the repository, so kopia would not be able to know WHEN to take the snapshot if the repository is not open.

I would recommend not using internal scheduler and using something like `crontab` to drive snapshot creation in this case.

**Comment by CrendKing** [comment]
I'm currently using OS scheduler achieve. Just wanted this feature to simplify the workflow.

Would it be possible to add this as per-client config? For example, when we do `repository connect`, specify the action script paths and store them in the config file? So that when user tries to access a, say NFS volume, this particular user can mount and unmount, while user who has the volume locally don't need to mount. I know it seems not clean, but could be useful.
