### ISSUE TITLE
[Feature Request] Make file creation date restorable

### ISSUE THREAD

**Issue by wechsler42** [kopia/kopia#1908]
Hi there,
I would like to suggest to make the file creation date restorable when I restore a file with Kopia. At the moment the situation within Kopia 0.10.7 looks like:

- file last modification date: preserved and restorable
- file last access date: preserved and restorable
- file creation date: preserved (?) and *not" restorable

Instead it uses the date of the file restoration itself as file creation date after a successful restore.
Thanks for consideration.

**Comment by jkowalski** [comment]
Kopia only has one modification time per entry - it's last modification time. The others are not well standardized across OSes, so this feature would require some non-trivial effort, but could be done.

PRs welcome.

**Comment by fresheneesz** [comment]
I agree this is really needed. I sort some of my files by creation date, so losing that isn't great. Can this feature request be opened and reconsidered?

**Comment by jonathanMelly** [comment]
Hello, I am also interested in that and am currently working on a PR, hoping to propose it as soon as possible...

**Comment by jonathanMelly** [comment]
Hi there, I recently opened the pullrequest #4994 and meanwhile I deal with copilot remarks and wait for any feedback from the maintainers you can already test the feature on your system, either by
- getting the code of #4994 and build the exe
OR
- Get my build [kopia experimental btime support](https://github.com/jonathanMelly/kopia/releases/download/v0.3x-btime-experiment1/kopiawindows-btime.exe)

**WARNING**: even if the modification should not cause any issue with other versions of kopia, **DO NOT USE IT** on your existing repos (unless you make a copy of them) because it will alter them and there is no guarantee that this feature will be integrated into kopia and if it is, it maybe in another way...

To validate this draft, you can copy an existing repo and try to create a new snapshot and then restore... Or create a test repo and see if it works... And give some feedback ;-)

**Comment by jonathanMelly** [comment]
> Kopia only has one modification time per entry - it's last modification time. The others are not well standardized across OSes, so this feature would require some non-trivial effort, but could be done.
> 
> PRs welcome.

@jkowalski Hello, I hope you do well and you're openness to PR is still welcome.
I opened  PR #4994 and dealt 3 times with copilot suggestions and would be glad to have some human feedback.

Could you reopen this issue if you still see value in it or share some "updated thoughts" about btime support now that there is a concrete suggested implementation ?
