### ISSUE TITLE
cross compile not working

### ISSUE THREAD

**Issue by durdin85** [kopia/kopia#1962]
Hi, kopia looks like nice tool so I wanted to give it a try, but to cover all my needs it need to support also 32-bit systems. It might sound weird in 2022, but it's still true. Anyway as there are no 32-bit binaries available, I was going to build kopia on my own.
What I've tested and works : cross compiling kopia on 64-bit linux resulting 32-bit windows binary.
What does not work for me : cross compiling kopia-UI on 64-bit linux resulting 32-bit windows/electron app.

Maybe I am doing it wrong, this is just my first day with kopia, but seems it assumes I am on windows, when I am trying to build binaries for windows, and so it tries to pick the windows-style paths, and assumes "powershell" exists. On my system I indeed have powershell, but it's called pswh instead. I've tried setting up the alias powershell=pwsh, even tried putting fake powershell binary into PATH, but with no luck. I've even tried tampering with Makefiles, modifying my environment, but it gets only worse. Last attempt:

```
$ env LANG=C GOOS=windows GOARCH=386 make kopia-ui
/bin/sh: 1: powershell: not found
/bin/sh: 1: powershell: not found
make -C app build-electron
make[1]: Entering directory '/home/durdin/dev/kopia/app'
/bin/bash: go: command not found
/bin/bash: go: command not found
go run github.com/kopia/kopia/tools/gettool -tool node:16.13.0 --output-dir /home/durdin/dev/kopia/tools/.tools/node-16.13.0
/bin/bash: go: command not found
make[1]: *** [../tools/tools.mk:138: /usr/local/bin/npm] Error 127
make[1]: Leaving directory '/home/durdin/dev/kopia/app'
make: *** [Makefile:114: kopia-ui] Error 2

$ # doing some steps manually works
$ go run github.com/kopia/kopia/tools/gettool -tool node:16.13.0 --output-dir /home/durdin/dev/kopia/tools/.tools/node-16.13.0
Downloading node version 16.13.0 from https://nodejs.org/dist/v16.13.0/node-v16.13.0-linux-x64.tar.gz...
2022/05/21 21:46:51 https://nodejs.org/dist/v16.13.0/node-v16.13.0-linux-x64.tar.gz checksum ok
$ which npm
/usr/bin/npm
$ which go
/opt/go/bin/go

```

**Comment by jkowalski** [comment]
Windows is not the main development OS for most folks here, so it's lagging behind.

We currently don't build UI for 32-bit Windows today, there are no strong reasons for it (other than the fact that in the last 15 years or so all new CPUs are 64-bit capable). If you can come up with a patch that makes such a package, I'll be happy to review it and merge. NodeJS and Electron have 32-bit versions available, so all this should be doable, you will definitely need to hack on gettool.go and the Makefile

Cross-compiling 32-bit Windows from Linux is notoriously hard, I'm not sure I would recommed attempting, but in our CI/CD Windows binary is built on a (64-bit) Windows machine, so that should be easier.

**Comment by durdin85** [comment]
Thanks for info. I'd try making a patch but I am not sure if I'll succed. I know very little of go and do not have build environment ready on windows, so it's even harder for me, but I'd try.
