### ISSUE TITLE
How to set/change encryption on a repository or set it manually when you create a repository?

### ISSUE THREAD

**Issue by heli-aviator** [kopia/kopia#2015]
This is a question first and foremost and not really an issu.

Hi, I'm wondering how I can change the encryption method for my kopia repository or make a new repo with specific encryption and block-hash?

I would like to change it to or make a new repo that has these options ```--block-hash=BLAKE3-256-128 --encryption=AES256-GCM-HMAC-SHA256```

I can't find anything on it in the documentation

**Comment by basldfalksjdf** [comment]
KopiaUI allows you to change these settings when creating a repo right there on-screen. For Kopia CLI, the documentation is fairly clear: https://kopia.io/docs/reference/command-line/common/ (scroll down to the repository create commands).

**Comment by heli-aviator** [comment]
Thank you for the answer, it helped me figure it out. Blake2 is default. 
At least for me.

I find the documentation a little lacking, like where do you use --use-keyring flag.

I cannot get --description to work either or --tags --progress

It would be nice if they made examples of full command string I.e. 
```
Kopia snapshot create --use-keyring --description test --tag :Documents -/Documents
``` 
Just so us non-programmers/newbie's have more to go on and don't have to ask questions here.

**Comment by basldfalksjdf** [comment]
I understand your point. However, this is a community project. The devs are busy improving this already awesome program. I understand there is a learning curve, as the documentation can be improved. Since this is a community project, I strongly recommend you help improve the documentation as you learn how to use Kopia. Even non-programmers can do that.

**Comment by heli-aviator** [comment]
I will definitely help if I can, but I first have to figure out how I can use those flags mention before. I'm trying to make it automated with the help of a script and cronetab.  But I can dugout out how to use the keyring feature or how to use a different script like encpass.sh to do it. Steep learning curve hehe I know the last one has nothing to do with kopia, but I don't want to store plane text password. I love kopia and I have tested it against borg and restock and it seems to be the one that fits my needs the best.

**Comment by ptandler** [comment]
> Thank you for the answer, it helped me figure it out. Blake2 is default. At least for me.

I also just noticed that Blake2-256-128 is the default (or was when I created my repo) but I now ran the benchmark and noticed that Blake3-256 is more than 3x faster on my machine (1.1 GiB/s -> 3.9 GiB/s), so I like to change this.

But I didn't find any documentation if / how the repo config can be changed _after_ it's created.

What I did find:

- [kopia content rewrite](https://kopia.io/docs/reference/command-line/advanced/content-rewrite/) "Rewrite content using most recent format" -> but does not seem what I'm looking for
- [repository upgrade begin](https://kopia.io/docs/reference/command-line/advanced/repository-upgrade-begin/) "Begin upgrade" -> no idea what it really does, maybe it's written somewhere else?

So, do I need to create a new repo and copy everything e.g. using [kopia repository sync-to](https://kopia.io/docs/reference/command-line/common/repository-sync-to-filesystem/)?

Once I understand how it works; I'll be happy to provide a PR to the docs :slightly_smiling_face: 

In fact, kopia is such a amazing backup tool, but to start using it requires to understand the concepts in order to take full advantage, so I really would like to help improving documentation. I remember that I already spent some time reading docs when I started with kopia, but it was months later I discovered the benchmark commands.

E.g. in case you really have to define these settings when a repo is created, the intro could mention that there are these benchmark commands already built into kopia. I just need to run them to see which parameters I should use. (While writing this: this could actually be part of the UI to provide a button to quickly run benchmarks when a repo is created and choose the best option based on this.)
