### ISSUE TITLE
Snapshot migrate or create errors when using server with APPEND only ACL for snapshots

### ISSUE THREAD

**Issue by RaveNoX** [kopia/kopia#2023]
Hello,

When using kopia server with this policies:
```
id:d62f711dd6c06759bb461c6b236b1fb0 user:*@* access:APPEND target:type=content
id:a0517d9124156b1cc86f83d09a0492e0 user:*@* access:READ target:type=policy,policyType=global
id:f1458d3121e5deefbb8cd6157b9aa820 user:*@* access:READ target:type=policy,hostname=OWN_HOST,policyType=host
id:f97b833fef122f824fd8be61c02fe0de user:*@* access:READ target:type=user,username=OWN_USER@OWN_HOST
id:dc3379322d56c3d6a29aaa1e14637240 user:*@* access:READ target:type=policy,username=OWN_USER,hostname=OWN_HOST
id:57691fe221d611e5df75feb9090f8c6e user:*@* access:APPEND target:type=snapshot,hostname=OWN_HOST,username=OWN_USER
```

On `snapshot migrate` or `snapshot create` error occurs because kopia tries to apply retention policy, but ACL denies it.
In my case it occured during checkpoint process, and investigation showed that reason is possible [here](https://github.com/kopia/kopia/blob/master/snapshot/snapshotfs/upload.go#L433).

It will be nice to have a flag which will totally disable retention policy apply for commands mentioned above.

**Comment by dodedodo** [comment]
I just encountered this as well. 

It would be really nice to have the kopia repository server apply the retention policy instead of the client. This way, a compromised client cannot overwrite or delete all its backups on the server, but the backups aren't stored forever. It's a solution to a problem that would normally be solved by a pull backup-scheme.

What do you think? Shall I open a new issue for this?

**Comment by maxximino** [comment]
IMHO this is a valid use-case, and shouldn't be marked as stale.

**Comment by Gui13** [comment]
Agreed
