### ISSUE TITLE
Dropbox support

### ISSUE THREAD

**Issue by danielskowronski** [kopia/kopia#2089]
Do you have any plans on adding more remote repositories support, especially Dropbox? I wasn't able to find any past feature request for it nor note that it's not feasible.

**Comment by basldfalksjdf** [comment]
Not sure when or if Kopia will support Dropbox natively (depends on if someone decides to submit a PR), but you can already use Kopia to backup to Dropbox by using `rclone`.

**Comment by danielskowronski** [comment]
That would be rclone to local directory synced by Dropbox daemon, right?

**Comment by basldfalksjdf** [comment]
There are two ways to use Kopia to store backups on Dropbox.

(1) Tell Kopia to store snapshots to a local directory that is synced by Dropbox (e.g., the Dropbox folder). Dropbox will handle the syncing to the cloud and Kopia will think it is backing up to a local folder. If you go this route, there are two things to keep in mind. 

First, you wanna make sure the snapshots stay local on your computer and are not made online-only with Dropbox. This is because Kopia regularly accesses its files, cleans up blobs, etc. and it thinks the files are readily available in the local folder. You could maybe get away with making the `p` blobs online-only, but I honestly would not recommend it -- you don't want to corrupt your backup by trying to shoehorn it to something that is not supported.

Second, if you ever have to restore, you will need to download the files locally before telling Kopia to restore from them. Kopia will not be able to restore directly from Dropbox.

(2) You can use `rclone` to setup a Dropbox `remote` location and then tell Kopia to save backups to that `rclone remote`. The process here is:

-Download `rclone` from https://rclone.org/
-Configure `rclone` to create a Dropbox `remote`: see https://rclone.org/dropbox/
-Create Kopia `repository` using the `rclone` option. This is available in KopiaUI or you can see https://kopia.io/docs/repositories/#rclone for the command line. You will need to enter two things: (i) the path to the `remote` you created earlier with `rclone` and the location of the `rclone` executable file.

The one thing to note about this latter option is that `rclone` support in Kopia is experimental because no one has tested Kopia to work with *all* providers that `rclone` supports. There are just too many, and many providers may do something slightly different than breaks Kopia support. So far, Kopia's `rclone` support has been tested to work with OneDrive and Google Drive. If it works with Dropbox, do let us know!

**Comment by danielskowronski** [comment]
That makes total sense, thanks for  thorough explanation. 

For some reason I though docs mentioned _rsync_, not _rclone_ which is very nice tool at first glance.

I'll take a look at it with Dropbox and let you know if it works as expected.

**Comment by basldfalksjdf** [comment]
I think @jkowalski was able to successfully test Kopia's `rclone` repo with Dropbox. So it should work.

**Comment by danielskowronski** [comment]
It works for me as well.

There's one issue when using KopiaUI with it, but I'll investigates it further before submitting separate bug if needed.
