### ISSUE TITLE
Refactor htmlui

### ISSUE THREAD

**Issue by phidevz** [kopia/kopia#2096]
Goal of this issue is to improve the code quality of htmlui.

Planned tasks:

1. Use function components instead of class components, where appropriate and easily implementable.
2. Use TypeScript as widely as possible.
3. Restructure files where appropriate.

**Comment by gitname** [comment]
@phidevz, I'm interested in helping with this endeavor. I am in favor of all three "planned tasks" and am also, as an alternative, interested in a rewrite as opposed to a refactor.

On a side note, on the Kopia Discourse forum (here: https://kopia.discourse.group/t/big-changes-coming-to-kopia-ui/820#issues-2), the owner of this repo expressed concern about introducing many NPM packages into the project, due to the increased risk of a dependency being compromised coupled with the fact that the UI runs as an Electron app, and so may have a higher level of access to the user's machine than a browser-based web app. One implication of implementing things locally instead of using a library, is that fewer people (on GitHub) may want to work on the project due to the need to invest time into learning a custom implementation of something vs. learning to work with a library that they might use again (e.g. Redux, Redux Saga, date-fns). I am in favor of scrutinizing packages before introducing them as dependencies, though. Some NPM packages have, indeed, been compromised/hijacked in the past (not necessarily ones used by Kopia--I mean packages on NPM in general).

**Comment by gitname** [comment]
>I am in favor of all three "planned tasks" and am also, as an alternative, interested in a rewrite as opposed to a refactor.

This could start out as a separate repository and then, if the owner of `kopiahtml` approves, eventually take the place of `kopiahtml` (and be moved into the `kopia` organization on GitHub). That way, development can take place without creating too much noise in the `kopia` organization and the Kopia creator's inbox.

**Comment by QazCetelic** [comment]
For other people interested in refactoring it to use TypeScript and perhaps add a few features such as a repo file size overview, I've created [a fork](https://github.com/QazCetelic/htmlui). You can test it with `env VITE_KOPIA_ENDPOINT=https://kopia.example.org npm run start`.

**EDIT: There are still some improvements to be made, but I've fully migrated it to TS**
