### ISSUE TITLE
The file size exceeds the limita allowed and cannot be saved - Windows 10

### ISSUE THREAD

**Issue by pauby** [kopia/kopia#2158]
If I mount a snapshot using the KopiaUI (0.11.2) then the snapshot is mounted.

![image](https://user-images.githubusercontent.com/12760779/177804208-fe366c97-d316-46fe-8992-3b1fefa5abff.png)

If I then try to copy files from the mounted snapshot I get this error:

![image](https://user-images.githubusercontent.com/12760779/177804983-3ec80af3-b1d2-46f5-a2a9-525999dbfbb7.png)

I did previously copy a file of approx 1MB over without issue. So the time limit looks to be related to the file size.

**Comment by xxxliqu1dxxx** [comment]
I think that's a WebDAV limitation - it should mainly for viewing/browsing purposes and not restoring by copy/paste. If you want to restore you can use the "restore" functionality within KopiaUI which will not be subject to this file size limitation.

**Comment by pauby** [comment]
If that is the case can we note it in the docs / Windows UI side of things?

**Comment by basldfalksjdf** [comment]
I am happy to update the docs to reflect such. Can someone please confirm this is a Windows-only issue due to how snapshots are mounted in Windows?

> If you want to restore you can use the "restore" functionality within KopiaUI which will not be subject to this file size limitation.

It may be worth creating a feature request to be able to bulk selectively restore from KopiaUI. Right now, mounting allows users to bulk selective restore via copy/paste, but if there is a size limitation on this, then another way to bulk selective restore would be handy.

Right now in KopiaUI, you can mount the snapshot, restore the whole snapshot, or selectively restore individual files -- but no bulk selective restore.

I wonder if adding bulk selective restore would be as easy as adding checkboxes when browsing snapshot contents?

**Comment by Spellshaper** [comment]
This is indeed an annoying limit in the native WebDAV client implementation on Windows that was never removed.
On Windows, mounted webDAV resources cannot be downloaded if their size exceeds 50MB. This can be slightly ameliorated by setting HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/services/WebClient/Parameters/FileSizeLimitInBytes to 4294967295 for the highest it can go at a limit of 4GB, which is still very low by modern standards.

I've been working around this issue so far by using another application to access the locally exposed webDAV resources:
Cyberduck: Good GUI client, not suitable for anything that expects a file path.
RaiDrive: Mounts WebDAV with their own file system implementation. May cache excessively which is a problem for larger files if there's not enough free space.

Issue #1249 asks if it's possible to use cgofuse probably for this reason. Using cgofuse would allow using WinFSP ([https://github.com/winfsp](url)) for mounting on Windows.

**Comment by basldfalksjdf** [comment]
I assume completely reworking how mounting works will take a bit of recoding. What about a temporary workaround that I assume should be a bit easier? Enable bulk selective restore. If one cannot copy/paste files from mounting, they can use bulk selective restore to get the files.

In KopiaUI, one can easily restore individual files but cannot easily restore whole folders or multiple files -- it is either mount, restore whole snapshot, or individual files. Bulk selective restore (i.e., the ability to restore multiple files/folders at once) would alleviate this problem.

I believe Kopia CLI can already selectively restore folders, but not sure if it supports bulk selective restore yet, so that may need some work too.

**Comment by Spellshaper** [comment]
Kopia CLI is capable of selective restore in a limited fashion - there's no include/exclude flag, but `--shallow` allows specifying how many directories deep to restore.
Using many subdir restores with `--shallow` in succession can kind of approximate basic include/exclude logic already.

**Comment by githubbapoopa** [comment]
https://github.com/kopia/kopia/issues/1249#issuecomment-1207459346

**Comment by VsevolodGolovanov** [comment]
The documentation says:
> Mounting is currently the recommended way of restoring files/directories from snapshots.

So I wasted a lot of time trying to restore files from a mount only to find out that it's impossible when it got to a 29 GB file...

**Comment by pauby** [comment]
From the comments (and the [last comment in particular](https://github.com/kopia/kopia/issues/2158#issuecomment-1309054534)) this hasn't been fixed as the docs still need updating.

Can this be reopened until it has been fixed?

@xxxliqu1dxxx did you get the answers to your [questions](https://github.com/kopia/kopia/issues/2158#issuecomment-1177759632) that would allow you to update the documentation?
