### ISSUE TITLE
Abillity to set UID and GID for Docker

### ISSUE THREAD

**Issue by onggie** [kopia/kopia#2195]
I have been playing around with the Docker version of Kopia, but it doesn't look like it accepts PUID/PGID and continues to use 65532:65532 as it's user and group. Is there anyway we can change this?

**Comment by tugdualenligne** [comment]
I might have the same issue, as I reported in the Logs issue 2171, where I get permission errors

**Comment by onggie** [comment]
> I might have the same issue, as I reported in the Logs issue 2171, where I get permission errors

Yep, it definitely seems like the same issue. The container hasn't been built to accept user and group. Is this a hard change, most containers support this feature.

**Comment by cstby** [comment]
I'd advocate for prioritizing this. 

I've run into quite a few issues because of the docker permissions:
- I ended up with a corrupted repository after a rsync copied the files it had permissions to read.
- Enabling ACL caused my kopia server to hang until I deleted the ACL rules AND modified the repository permissions.
