### ISSUE TITLE
Docker 'Actions' 

### ISSUE THREAD

**Issue by esticle** [kopia/kopia#2238]
Hi,

I got everything backup wise working just fine in Docker, however I'm unable to do any of the 'Actions' which call on secondary scripts 

![image](https://user-images.githubusercontent.com/8289941/181248165-5b8ac804-7d81-402a-a6dd-a2e901efde00.png)

Regardless of the command it will always fail, even built-in ones such as 'echo', shell-scripts claims it cannot be found (yes volumes are exported correctly), etc. any ideas?

Thanks!

**Comment by jkowalski** [comment]
That is because Docker image is not based on any particular linux distrubution (we use `gcr.io/distroless/static:nonroot` bsae), so it does not include any tools inside it. It currently only has `kopia` and `rclone` binaries and few other config files, but literally nothing else - this is to keep the image size small and to harden the security of the container as is now a standard practice.

You currently have the following options:

1. Rebuild kopia image using a different base image (replace first line of `Dockerfile` with `FROM ubuntu:latest` and rebuild using the `docker-publish.sh` script)
2. Create your own image from Kopia base image and add tools that you need.
3. Mount required tools from another linux distribution as volume mounts. Those need to be statically compiled or else you need to provide libraries as well.
4. Don't use the container at all - Kopia is literally a single, statically-linked binary that might give you the same or better experience without a container.

We'll may consider providing something like Ubuntu-based or Alpine-based image which will include some additional Unix tooling. PRs are welcome.

**Comment by esticle** [comment]
> That is because Docker image is not based on any particular linux distrubution (we use `gcr.io/distroless/static:nonroot` bsae), so it does not include any tools inside it. It currently only has `kopia` and `rclone` binaries and few other config files, but literally nothing else - this is to keep the image size small and to harden the security of the container as is now a standard practice.

Perfect, thanks for the response and detail, that does explain a lot! I will have a ponder, thanks!
