### ISSUE TITLE
Actions/ZFS point-in-time snapshotting: unclear description of task

### ISSUE THREAD

**Issue by sssheridan** [kopia/kopia#2291]
I'd rate myself as an intermediate-level user of both ZFS and Kopia. I don't understand what task is being described here:

> ### ZFS point-in-time snapshotting:
> When snapshotting ZFS pools, we must first create a snapshot using zfs snapshot, mount it somewhere and tell kopia to snapshot the mounted directory instead of the current one.

- First of all, the phrasing "When snapshotting ZFS pools, we must first..." makes is sound like I _must_ follow these extra steps if I want to use Kopia to back up a ZFS pool that's also got scheduled snapshots.
- I think a clearer "When ________" statement would clarify this. Is this talking about Kopia backing up a current snapshot of the pool, or an old one?
- What does this procedure do that wouldn't be achieved by scheduling regular snapshots of the ZFS pool and regular backups with Kopia?

Appreciate any clarification.

**Comment by basldfalksjdf** [comment]
The [page you reference](https://kopia.io/docs/advanced/actions/) is describing taking a ZFS snapshot before Kopia runs its own snapshot. I suspect the confusion is because "snapshot" is used to describe two distinct tasks here. 

Maybe this will help clear the confusion.

You can tell Kopia to backup a ZFS pool, no problem. Just create a policy to backup the files in the ZFS pool, and Kopia will do its thing. You do not need to do anything that is described on the page you reference. 

However, the way Kopia works is that it will backup files in the state that they are as of the time that Kopia scans the file and not the state that the files are as of the time that Kopia starts its snapshot. For example, let's say Kopia is scheduled to start a snapshot of Files A to Z at 1:45pm. Let's say File Z is in State 1 at 1:45pm. Let's also say that Kopia gets to File Z at 1:48pm and, by that time, File Z is in State 2. In this situation, Kopia will backup File Z in State 2, because State 2 is the state of File Z when Kopia scans the file. 

If you want to ensure that Kopia backs up files in their states as of the time of the Kopia snapshot or if you want to backup locked files, you can enable ZFS/VSS/BTRFS/APFS snapshotting. This allows Kopia to not only backup locked files that normally would not be backed up, but also ensures that all files are backed up in the state that they are as of the time that Kopia starts its snapshot -- which would be 1:45pm in the above example.

Kopia currently does use ZFS/VSS/BTRFS/APFS snapshotting by default. If you need the feature, you can enable it using Kopia's `actions` feature, such as described at https://kopia.io/docs/advanced/actions/.

I hope that make sense.

P.S. The devs put their own free time into Kopia + documentation. I would suggest having less... attitude... in your inquires for help.

**Comment by sssheridan** [comment]
> P.S. The devs put their own free time into Kopia + documentation. I would suggest having less... attitude... in your inquires for help.

Apologies, I just meant to be as direct/clear as possible, no attitude was intended. These aren't inquiries for help; I intended them as a (lesser) contribution to the same project - reporting on bumps, and suggesting where the documentation can be improved. If my comments have been too minor/nitpicky for this stage in development, please let me know. And in any case, I can try to make my intentions clearer in the future.

**Comment by basldfalksjdf** [comment]
It is cool, no worries.

Also, I agree that the docs can be rewritten for clarity.

**Comment by M0rtenB** [comment]
> Kopia currently does use ZFS/VSS/BTRFS/APFS snapshotting by default. If you need the feature, you can enable it using Kopia's `actions` feature, such as described at https://kopia.io/docs/advanced/actions/.

I’m confused. Does Kopia utilize APFS snapshots automatically, or did a typo sneak in?

**Comment by julio-lopez** [comment]
Typo. Kopia does NOT use the FS snapshotting mechanism by default.
