### ISSUE TITLE
kind kopia and other tools benchmark report

### ISSUE THREAD

**Issue by deajan** [kopia/kopia#2375]
Hello,

I'm currently doing benchmarks for deduplication backup tools, including kopia.
I decided to write a script that would:
 - Install the backup programs
 - Prepare the source server
 - Prepare local targets / remote targets
 - Run backup and restore benchmarks
 - Use public available data (linux kernel sources as git repo) and checkout various git tags to simulate user changes in the dataset

The idea of the script would be to have reproductible results, the only changing factor being the machine specs & network link between sources and targets.

So far, I've run two sets of benchmarks, each done locally and remotely.
You can find the results at https://github.com/deajan/backup-bench

I'd love you to review the recipe I used for kopia, and perhaps guide me on what parameters to use to get maximum performance.
Any remarks / ideas / PRs are welcome.

I've also made a comparaison table of some features of the backup solutions I'm benchmarking.
I still miss some informations for some of the backup programs.
Would you mind having a look at the comparaison table and fill the question marks related to the features of kopia ?
Also, if kopia has an interesting feature I didn't list, I'll be happy to extend the comparaison.

PS: I'm trying to be as unbiased as possible when it comes to those benchmarks, please forgive me if I didn't treat your program with the parameters it deserves.

Also, I've created the same issue in every git repo of the backup tools I'm testing, so every author / team / community member can judge / improve the instructions for better benchmarking.

**Comment by phidevz** [comment]
Hallo @deajan ,

awesome project! 

Note before continuing my answer: I am not too deep into the details of how Kopia works, but I use it for reasonably large datasets and both remote as well as local.
After quickly looking through your setup script, I have noticed:
* You have set the global policy to use zstd as compression. IIRC from the Kopia docs, the benchmarked algorithms almost always brought out the s2 compression as superior (at least in terms of speed). I personally use `s2-default` exclusively, combined with a minimum file size of `1024` (I do not think that would make sense in the benchmark though).
* You have set to ignore the `.git` folder. I think it would be sensible to include this folder because this is also a very special kind of "workload" for the backup software (many many small files; and as far as I could see, you already worked on "normal" files by using the checked out git repositories as well as "large" files by tar-ing the entire repo). For me at least, that also has a practical application: I have my own gitea instance running, which means there are a lot of `.git` folders in gitea's Docker volume (I backup my entire volumes folder)

That is all I can think of right now. Hope that helps!

Best regards

**Comment by deajan** [comment]
@phidevz Thanks for your input.
Indeed I began comparing all solutions with a common compressor, being zstd. Of course, that being, done, I can now try to fine tune every program to achieve it's best.
I tried `kopia benchmark compression` on my source server, it looks indeed that s2 is best for my dataset.
```
     Compression                Compressed   Throughput   Allocs   Usage
------------------------------------------------------------------------------------------------
  0. s2-default                 19.4 KiB     466 MiB/s    14216    6.7 MiB
  1. s2-parallel-4              19.4 KiB     464 MiB/s    14191    6.6 MiB
  2. s2-parallel-8              19.4 KiB     463.8 MiB/s  14198    5.7 MiB
  3. s2-better                  16.8 KiB     262.2 MiB/s  14422    2.7 MiB
  4. deflate-best-speed         15.1 KiB     172 MiB/s    26       833.7 KiB
  5. zstd-fastest               14.3 KiB     161.9 MiB/s  367      6.1 MiB
  6. gzip-best-speed            15 KiB       116.2 MiB/s  32       1.2 MiB
  7. deflate-default            13 KiB       96.9 MiB/s   26       1.1 MiB
  8. zstd                       13.4 KiB     82.8 MiB/s   377      15.8 MiB
  9. pgzip-best-speed           15.1 KiB     65.2 MiB/s   67242    7.2 GiB
 10. pgzip                      13 KiB       48.5 MiB/s   68868    7.5 GiB
 11. zstd-better-compression    13 KiB       46.2 MiB/s   404      297.1 MiB
 12. gzip                       12.4 KiB     37.3 MiB/s   30       833.9 KiB
 13. gzip-best-compression      12.4 KiB     26.8 MiB/s   30       833.9 KiB
 14. deflate-best-compression   12.3 KiB     22.2 MiB/s   28       1.1 MiB
 15. pgzip-best-compression     12.3 KiB     17.6 MiB/s   71324    7.7 GiB
```

I have to ignore the .git folder, since it contains all file revisions since the beginning.
If I didn't ignore it, I would not be able to simulate user changes between my dateset properly.
I will also do a sparse file dataset benchmark in not so long.

**Comment by adowair** [comment]
This is a great project, and glad to see those results =) 

> I will also do a sparse file dataset benchmark in not so long.
To simulate this one properly, do remember to use `--restore-files-sparsely` in your snapshot restore command. I'm really curious to see how that will perform.

**Comment by jkowalski** [comment]
@deajan Kopia 0.12.0 is now out at https://github.com/kopia/kopia/releases/tag/v0.12.0

I'd love to see your benchmark updated with this.

**Comment by deajan** [comment]
@jkowalski Benchmark will be updated soon. I'll keep you posted.

**Comment by deajan** [comment]
@jkowalski Backup benchmarks updated. Also added new qemu use case benchmark.

**Comment by julio-lopez** [comment]
@dejan kopia encrypts all of its metadata and data structures
