### ISSUE TITLE
kopia list returns inconsistent results on Idrive E2

### ISSUE THREAD

**Issue by ajctrl** [kopia/kopia#2426]
It seems kopia with IDrive e2 is not working anymore.

**Comment by adowair** [comment]
Can you give more details? Do you have steps to reproduce some failure?

**Comment by ajctrl** [comment]
yes, you just have to create a new repository in KopiaUI v0.11.3 and wait less than an hour.

**Comment by adowair** [comment]
Is there a specific failure that you are seeing (perhaps snapshot fails, or cannot connect to repo)? Could you share the details/config of your setup (removing PII)? Without more detail, it'll be very difficult to go about reproducing and debugging failures.

**Comment by ajctrl** [comment]
Kopia it self didn't give me any message when it delete everything.
After that,
snapshot list
policy list
user list
every result is null.
I confirmed such things doesn't happen in backblaze B2.

**Comment by adowair** [comment]
Can you confirm whether this is also happening with KopiaUI `v0.11.2` or prior? Could you share the exact steps (with screenshots if they're relevant) to get to where you are?

**Comment by ajctrl** [comment]
i tested with apk add kopia in alpine linux, it was v10, docker kopia:latest too.

**Comment by adowair** [comment]
To be sure, are you saying that between the first and second `kopia policy list`, the output is different?

**Comment by ajctrl** [comment]
yes, it gives me something like this for a while
7ff6dc1d4761f52fa79efa9597ae53cd (global)
in the end, null response

**Comment by ajctrl** [comment]
to be sure, not only kopia policy list,
snapshot list
in server mode, user list, acl list too

**Comment by jjo21631** [comment]
I can confirm. This happens consistently. Create e2 Repo. Set profiles. Create snapshot. Estimate and start 1st snapshot. At some point the snapshot chokes and dies. Go back and look at Repo, no snapshots, no profile, nothing - empty. Only repo exists. Log into e2, look at bucket and there's files there, so something is apparently causing data to be screwed up.

So, I tried this.... Create repo, profile and detach. Connect back to repo and there's nothing there. Profiles are gone.

Anything anyone would like me to try. Running 11.3 UI. Have no problems with Wasabi or local drive Repos. Definitely Idrive e2. It worked up until today. It must be on their side. I changed no Kopia software.

Let me know.

**Comment by dimejo** [comment]
Can you try running `kopia repo validate-provider`? Does it print any errors?

**Comment by cirrusflyer** [comment]
I'm seeing this same issue over the past couple days.

**Comment by cirrusflyer** [comment]
So in my case, my custom global policy seems to be gone.  Checked this on two servers.

**Comment by vsorin1000** [comment]
I can confirm, this happened to me also. Snapshot and all policies gets deleted from the UI, but files are preserved on the E2 bucket. Using v0.12.0-rc1 atm, but got the same thing on v0.11.3.

**Comment by cirrusflyer** [comment]
I'm also using object locking with Kopia since E2 supports this.  I'm wondering if this is related?  Any one else using object locking also having issue losing their policy and snapshots but retaining files?

**Comment by jjo21631** [comment]
With or without Object Locking e2 seems to not be compatible any longer. E2 side has changed and I reported to idrive,  I think the product is really not ready for prime time.

**Comment by GUI** [comment]
I think something has broken on IDrive E2's end and they're no longer properly handles prefix list queries, which is what's breaking this. I've reached out to IDrive support about this, but here's what I think is going on: `kopia --log-level debug snapshot list --all` shows various results like this where `ListBlobs` is returning 0 results:

```
DEBUG [STORAGE] ListBlobs	{"prefix":"xn0_","resultCount":0,"error":null,"duration":"43.162313ms"}
DEBUG [STORAGE] ListBlobs	{"prefix":"xn1_","resultCount":0,"error":null,"duration":"53.767013ms"}
``` 

However, if I list all of the files, I do see files that start with `xn0_` or `xn1_`. It seems like IDrive E2 no longer respects `prefix` queries unless it's matching a full filename, so it won't return any results if the `prefix` is a partial match.

This issue can also be demonstrated with the aws CLI `aws s3api list-objects-v2` command. Let's say you have a bucket `my-bucket`, and a file named `foo/bar` inside. Against any other S3 provider, `aws s3api list-objects-v2 --bucket my-bucket --prefix foo/b` will return the `foo/bar` object. However, against E2 as of sometime around September 19, this no longer returns any results. `--prefix foo/bar` will return a result against E2, so it seems to only match full file names, rather than a prefix.

**Comment by vsorin1000** [comment]
Seems that now it's working as it should be. Can someone else test it ?

**Comment by GUI** [comment]
Yup, I just heard back from IDrive support that it should be fixed and to test again. Things appear to be working for me now too.

**Comment by ajctrl** [comment]
Thank you very much!

**Comment by cirrusflyer** [comment]
Seeing iDrive e2 issues again. Anyone else?
