### ISSUE TITLE
KopiaUI: Windows + SFTP + known_hosts: extremely not userfriendly

### ISSUE THREAD

**Issue by knutov** [kopia/kopia#2444]
It seems it is not possible to add SFTP repository in Windows in KopiaUI without manually creating known_hosts file with correct content.

Also, field with path to known_hosts does not support selecting file via user dialog, and does not support path variables (like `%USERPROFILE%`).

Why it requires known_hosts file at all? For example, WinSCP asks if I'm ok with fingertips and saves answer in some internal database.

May be it was fixed for command-line client - https://github.com/kopia/kopia/issues/500 but it is still relevant for UI version.

**Comment by basldfalksjdf** [comment]
Is this true? I have connected to SFTP repos via KopiaUI without filling out `known_hosts` before.

Perhaps a rework of the screen is needed where the required fields are clear.

**Comment by knutov** [comment]
![изображение](https://user-images.githubusercontent.com/255869/192369187-78cd2061-72d1-4728-b017-080b7c339389.png)

Always shows error unless properly filled

**Comment by ingul-buz** [comment]
I concur this a slightly irritating feature. On Windows it's quite common that a user doesn't have a known_hosts file at all. There's no uniform way for Windows' ssh/scp/sftp clients to save the public keys of hosts, most of them save that data their own ways (e.g. amongst their own data, Windows registry etc.). There _**is**_ an OpenSSH client in Windows since Windows 10, but not many know it even exists, let alone have used it. Many Windows users don't feel comfortable with a command line tool anyway.

It would be great if Kopia checked the existence of known_hosts from its common location (on Windows `%USERPROFILE%\.ssh\known_hosts`), and should it not exist (or the needed key is not saved yet), would prompt the user to accept the key fingerprint, then save it and use it from there on. But I realize that would probably require quite a lot of changes in Kopia and the way it's structured.

Of course there's the external ssh client option, but even that requires you to first connect to the host with the client and gather the public key before you can use it with Kopia. Admittedly it will be easier after that phase.

Another way would be to include a checkbox/command line option (with appropriate warnings as to why it's regarded a Bad Thing) in order not to require a known_hosts at all. As long as it's mandatory, many Windows users will hit the wall right there.

@basldfalksjdf, are you really saying you have managed to go on without ever defining a known_hosts? AFAICS it's required everywhere (`--known-hosts` or `--known-hosts-data` on the repo connect options). Maybe you did it when you connected the first time, and now the info is saved in your config file?

**Comment by knutov** [comment]
Why it is mandatory at all?

Most users never actually check/compare fingerprint and just always hit "yes" and for most end users it doesn't matter. So why not to make it comfortable to them and have an optional option fot those who aware more about security?

Being not friendly in this case lead to not making backup at all, I think, because it's "too complex" and problem may be never happened.

**Comment by ingul-buz** [comment]
Yes, it's true that it's too easy to just accept everything you get prompted about. I'm guilty of it myself occasionally.

In this case I think the main idea is that once you have accepted the host key for the first time, it should make you suspicious if you get prompted about the same thing anytime later. Hosts don't change their keys that often, and this is just a security measure to let you know you're still using the right host. Kopia simply doesn't connect if the key has changed.

Nevertheless, I would support making this optional, simply because it may become too difficult for an average Windows user to figure it all out. But preferably defaulting the way that you would have to explicitly opt _out_ from using a known_hosts, not the other way round. Probably even we Windows users would be able to get away with that ;-).

**Comment by knutov** [comment]
Any default option is ok, I think, but non-difficult way should exists to make it possible to use.

Frequently key changes are possible in some scenarios, for example when storage servers are migrating to each other to balance disk usage while domain for server repo remains the same (example: `user123.domain CNAME storage567.domain`)

**Comment by basldfalksjdf** [comment]
> @basldfalksjdf, are you really saying you have managed to go on without ever defining a known_hosts? AFAICS it's required everywhere (`--known-hosts` or `--known-hosts-data` on the repo connect options). Maybe you did it when you connected the first time, and now the info is saved in your config file?

Hmm, perhaps not. I don't regularly use SFTP and tried it a while back. I swear I did not have this issue, but I may be misremembering it!

**Comment by th0mp50n** [comment]
I tried KopiaUI+sftp on Windows some weeks ago and had same experience as @knutov .

Currently trying on Ubuntu with KopiaUI Version v0.12.1, same thing:
![image](https://user-images.githubusercontent.com/1233492/199347560-8472e95b-a961-483d-b0a0-a5c16a193e48.png)

Seems to me it's just a mandatory field now, which is inconsistent with documentation at https://kopia.io/docs/repositories/#sftp :
> You can optionally enter Path to known_hosts file

**Comment by ingul-buz** [comment]
I actually hadn't noticed that the documentation claims this feature to be optional, but so it does. Now it's time to make it optional in the real life. Please. I would be happy to try and do it myself, but I don't have the skills for it.

The problem is that you always have to make an ssh connection to your host with an appropriate external SSH client in the first place in order to collect the known_hosts data and create the file. It's not hard to do, but many people just don't know how to do it.

**Comment by braadaaay** [comment]
Just set up my kopia instances on 3 servers and noticed the same thing. For me, it's not an issue that you have to specify the hosts file, but in my opinion it **should** auto populate with the system default (i.e. /home/$USER/.ssh/known_hosts or /root/.ssh/known_hosts for linux, and C:\Users\%USERNAME%\.ssh\known_hosts) with the option to change it.

Nevertheless, this should be documented more, as well as explicitly warning that the user must have already previously connected to the SSH host as it wasn't very intuitive for me the first time around.

**Comment by sunbl0ck** [comment]
So is there a solution? I don't even know how to create a hosts file or what to put in there.
Can someone point me in the right direction?

**Comment by braadaaay** [comment]
> So is there a solution? I don't even know how to create a hosts file or what to put in there. Can someone point me in the right direction?

@sunbl0ck All you need to do is connect to the destination via SSH then disconnect, this will add the connection to the known_hosts file. Then specify the known_hosts file using one of the following:

1. If you're working on a Windows PC, use **C:\Users\%USERNAME%\.ssh\known_hosts**
2. If you're working on Linux, and login with root use **/root/.ssh/known_hosts**
3. If you're working on Linux but another user, use **/home/[yourUserName]/.ssh/known_hosts** (replace [yourUserName])

**Comment by sunbl0ck** [comment]
The problem is I'm on Unraid. It's linux based, but I don't have a root folder

**Comment by braadaaay** [comment]
@sunbl0ck that's outside the scope of this thread then. I suggest you start a new thread, since this is Unraid specific.

**Comment by BLu85** [comment]
There is a lot of information missing in the documentation and it seems very complicated and difficult to achieve simple things like setting up an sftp connection.

**Question**: what is the procedure needed to set up an sftp connection from the KopiaUI? What files and information are needed?

So, from the documentation:
```
$ kopia repository create sftp \
        --path=... \
        --host=... \
        --username=... \
        --keyfile=...
```

This does not work in Linux, as the --known-hosts= is required (yes, it is mentioned in the documentation, but it is mandatory, so it should be put in the command).

So, adding the --known-hosts=file_to_known_hosts kopia connects to the remote.

The most irritating things is that I still haven't found a way to connect to the same sftp server using the KopiaUi.
It asks for redundancy information:

- the path of the private key (OK)
- the content of the private key (**redundant**, why is it needed?)
- the path to the known hosts file (not needed when connecting from a bash via sftp)
- the content of the known hosts (**redundant**, why is it needed?)

Even adding this information, KopiaUi doesn't connect to the server. 
The funny thing is that I closed and reopened the KopiaUi and magically the GUI was connected. So I did the process from scratch to understand what was the right procedure, and I am now not able to reconnect.

I think the GUI and the documentation is extremely poor. I understand it is an Open Source project, but if you want other people to use it, a good and well explained documentation is mandatory.
It seems I am not the only one requesting a better documentation (and a flawless sftp conneection procedure).

Thanks,
Luca

**Comment by BLu85** [comment]
> > So is there a solution? I don't even know how to create a hosts file or what to put in there. Can someone point me in the right direction?
> 
> [@sunbl0ck](https://github.com/sunbl0ck) All you need to do is connect to the destination via SSH then disconnect, this will add the connection to the known_hosts file. Then specify the known_hosts file using one of the following:
> 
>     1. If you're working on a Windows PC, use **C:\Users%USERNAME%.ssh\known_hosts**
> 
>     2. If you're working on Linux, and login with root use **/root/.ssh/known_hosts**
> 
>     3. If you're working on Linux but another user, use **/home/[yourUserName]/.ssh/known_hosts** (replace [yourUserName])

It clearly doesn't work, hence the reason of this topic. It only works via the command line, but not via the KopiaUI.
Why was this issue closed? It hasn't been resolved yet.

**Comment by iamGBOX** [comment]
Nearly a year on, just dealt with this again myself. I was able to circumnavigate the mess by pulling the contents of my `known_hosts` on the host, but again, this is poorly explained and telegraphed in the UI.
