### ISSUE TITLE
Snapshot delete does not free up space

### ISSUE THREAD

**Issue by MBeggiato** [kopia/kopia#2608]
When deleting snapshots, the space on my storage is not freed up.
Is this a error on my side?

**Comment by AgeAison** [comment]
Space will only clear up when the full maintenance runs, which by default is once every 24 hours. You can manually run the maintenance to immediately clear up the space, though due to safety reasons maintenance will only clear data once enough time has passed, so you would most likely have to turn the safety off. 
You can run this command `kopia maintenance run --full --safety=none` to delete the old snapshots.

See https://kopia.io/docs/advanced/maintenance/

**Comment by MBeggiato** [comment]
> Space will only clear up when the full maintenance runs, which by default is once every 24 hours. You can manually run the maintenance to immediately clear up the space, though due to safety reasons maintenance will only clear data once enough time has passed, so you would most likely have to turn the safety off. You can run this command `kopia maintenance run --full --safety=none` to delete the old snapshots.
> 
> See https://kopia.io/docs/advanced/maintenance/

Thank you so much!

**Comment by IPlayZed** [comment]
For me the space was not freed even when running it with `--safety=none`.

I have deleted the snapshot with `kopia snapshot delete k151a37c19bf23f48bd00b22ebe541aff --delete` and ran the maintanance:

```
❯ kopia maintenance run --full --safety=none
Running full maintenance...
Looking for active contents...
Looking for unreferenced contents...
GC found 65 unused contents (271.7 KiB)
GC found 0 unused contents that are too recent to delete (0 B)
GC found 331751 in-use contents (240.6 GiB)
GC found 12 in-use system-contents (6.8 KiB)
Rewriting contents from short packs...
Found safe time to drop indexes: 2022-12-02 21:30:13.518866169 +0000 UTC
Dropping contents deleted before 2022-12-02 21:30:13.518866169 +0000 UTC
Looking for unreferenced blobs...
Deleted total 25 unreferenced blobs (61.4 MB)
Cleaned up 0 logs.
Cleaning up old index blobs which have already been compacted...
```

It says that `GC found 331751 in-use contents (240.6 GiB)` as you see, that is not true, as I list the snapshots, it return exactly none... Now I am stuck with 240.6 GiB of used trash space.

**Comment by AgeAison** [comment]
Are you sure there are NO snapshots that use this data? Keep in mind due to deduplication, it's possible for a completely different snapshot (even of a different path) to still be using this data, so obviously in that case the blobs would not be cleared.

You can do `kopia content stats` to get an overview of everything that's currently stored in the repository to make sure it's actually empty.

> as I list the snapshots, it return exactly none

If you actually have no snapshots at all in the entire repository, then that is truly weird. I don't know what is causing that in this case, but you could just delete the whole repository and recreate it for a quick fix.

However it would be best for you to create a new issue here and post a bit more details about your setup, so you can be better helped.

**Comment by Adam-Color** [comment]
> Are you sure there are NO snapshots that use this data? Keep in mind due to deduplication, it's possible for a completely different snapshot (even of a different path) to still be using this data, so obviously in that case the blobs would not be cleared.
> 
> You can do `kopia content stats` to get an overview of everything that's currently stored in the repository to make sure it's actually empty.
> 
> > as I list the snapshots, it return exactly none
> 
> If you actually have no snapshots at all in the entire repository, then that is truly weird. I don't know what is causing that in this case, but you could just delete the whole repository and recreate it for a quick fix.
> 
> However it would be best for you to create a new issue here and post a bit more details about your setup, so you can be better helped.

I am having this issue now too, annoying...

**Comment by IPlayZed** [comment]
Unfortunately, I am not using this setup anymore so I can not help and replicate this issue.

**Comment by skironDotNet** [comment]
I actually "tested" it. Had a backup of 2 VMs with total 74GB, deleted both snapshots completly, taken a new ones after shrinking the vdi file, the size should be 60GB. Nothing has changed. I'm talking about automatic maintenance 

<img width="1190" height="803" alt="Image" src="https://github.com/user-attachments/assets/ecc5c14c-13d8-41ef-a571-03fc6a7464e1" />

When run the command explicitly it did free up the space

<img width="601" height="657" alt="Image" src="https://github.com/user-attachments/assets/1474313c-4919-46e4-bc0d-f220d741f728" />

 So the free up is possible but it's not done automatically when using kopia server mode
