### ISSUE TITLE
rclone-v1.61 does not work anymore with kopia

### ISSUE THREAD

**Issue by kapitainsky** [kopia/kopia#2655]
problem as in the title - reverting to rclone-v1.60 fix the problem

**Comment by fivestones** [comment]
When I try to connect with kopia to a previously created repository, `kopia repository connect rclone...`, I get `got error BLOB not found when WriteTemporaryFileAndCreateParentDirs` 10 times, and then `unable to persist sharding parameters: unable to complete WriteTemporaryFileAndCreateParentDirs despite 10 retries: BLOB not found`.
I think this is because of this bug?
I am running rclone 1.61.1, kopia 0.12.1 build: 5227d74996b6520f9f96e4203cfe00b832a60d5f

**Comment by kapitainsky** [comment]
testing 13RC2 and indeed it works now again with the latest rclone.
