### ISSUE TITLE
"kopia maintenance run --no-full" still runs full maintenance

### ISSUE THREAD

**Issue by 0x53A** [kopia/kopia#2775]
```
> .\kopia maintenance run --no-full
Running full maintenance...
Looking for active contents...
```

I believe the issue is the ``||`` here:
https://github.com/kopia/kopia/blob/fba03c98828363f46e46558041757a5378036b98/cli/command_maintenance_run.go#L36-L38

The fix would probably be to change from boolean to tristate (``bool?`` in c#)

**Comment by TheWiresharkGuy** [comment]
Any updates on this?

**Comment by Gui13** [comment]
From my exploration of the source code, it looks like the light maintenance is not necessary when the Epochmanager is available:

https://github.com/kopia/kopia/blob/1e975743913f6c0e630f275edfd132e938e9fee2/repo/maintenance/maintenance_run.go#L250-L251 

So it makes sense that the maintenance is "forced" to Full if your repository has the Epochmanager support.

I think this issue is not an issue :D

**Comment by julio-lopez** [comment]
Dup: #3600
