### ISSUE TITLE
Documentation on ignoring files a bit confusing

### ISSUE THREAD

**Issue by Shellfishgene** [kopia/kopia#3123]
Hi!
On https://kopia.io/docs/advanced/kopiaignore/ the example config file comments say:
```
# Ignoring all files and folders within the "thesis/logs" directory
/logs/*
```
while the text below that says "The second rule, /logs/* ignores all files within the logs directory."

I think the first is not correct, for ignoring all subfolders in addition to the files `**` is needed? Either way, it may be a bit confusing.

**Comment by lupusA** [comment]
Hi @Shellfishgene, 

i wrote the documentation on kopiaignore files. The second rule "/logs/*" indeed ignores all files within the _logs_ folder within the root directory. This is also stated in the explanation. 

"The second rule, /logs/* ignores all files within the logs directory. Only the logs directory at the root will be ignored as the rule begins with a /."

What would you like to be changed?

Cheers,

**Comment by lupusA** [comment]
Hi @Shellfishgene ,

i just tested it again as i was also thinking about it :-). 

Adding _/logs/*_ to the kopiaignore file will lead to ignoring all files and folders within that folder. The asterisk makes sure, that also the folders below are ignored. 

`

17:12:14.570 excluded file logs/fail.log (0 B)
17:12:14.571 excluded file logs/gen.log (0 B)
17:12:14.571 excluded file logs/log.db (0 B)
**17:12:14.571 excluded dir logs/test**
17:12:14.571 excluded file logs/tmp.db (0 B)
17:12:14.571 excluded file logs/tmp.dba (0 B)
`

However, if you have a _logs_ folder somewhere else, say _thesis/tmp/logs/_ this folder will not be ignored. For this you need the double asterisk "**".

Hope it helps. 

Cheers,

**Comment by Shellfishgene** [comment]
Thank you!

**Comment by kdkasad** [comment]
> i wrote the documentation on kopiaignore files. The second rule "/logs/*" indeed ignores all files within the _logs_ folder at the _root_ (thesis) directory. As no other folders are placed inside _logs_ it should work as stated in the explanation:

I know this is an old issue (and I'm happy to open a new one instead of continuing here), but I just started using Kopia and found the ignore documentation a little confusing. It says the `root` directory, but doesn't clarify what that is. I think it would be helpful to specify that it means the directory in which the `.kopiaignore` file is located, or the directory a policy refers to if the ignore rule is part of the policy and not in a `.kopiaignore` file.

The latter note about policy ignore rules should be confirmed by someone with more experience with Kopia before adding to the docs. From my testing, it appears that that's how resolution works, but I haven't verified by reading the code (yet).
