### ISSUE TITLE
isCreate flag is not utilized in function

### ISSUE THREAD

**Issue by funkycode** [kopia/kopia#3181]
https://github.com/kopia/kopia/blob/e512731d729bf365a087de2907e89acd3fc2c873/repo/blob/s3/s3_storage.go#L339

My expectation were that if you pass the flag and in case bucket doesn't exit it would be created, but seems that this value in function is not used

**Comment by julio-lopez** [comment]
Correct, the `isCreate` flag is not used in the S3 provider. It is used in other providers that need to perform some work when creating the repository. In the case of S3, and other blob stores, nothing needs to be done at this layer when creating the repository.

kopia does NOT create buckets for the repository, this is by design. The bucket needs to already exist when creating a kopia repository. The bucket creation needs to be done before using another tool such as the Minio CLI or AWS CLI.

**Comment by funkycode** [comment]
Well it is fair enough, but it is misleading.
I would assume it is done to keep same signature of function, but in this case I would consider maybe moving it to options or at least add comment/documentation that it is not used where it is not
