### ISSUE TITLE
Permissions errors on macos

### ISSUE THREAD

**Issue by cooperaj** [kopia/kopia#327]
When attempting to do a backup of my home folder I see this:

```
[31m13:26:07.188 [kopia/server] upload error: unable to process directory "Library": unable to process directory "Containers": unable to process directory "com.apple.mail": unable to process directory "Data": unable to stat directory entry "DataVaults": lstat /Users/USERNAME/Library/Containers/com.apple.mail/Data/DataVaults: operation not permitted[0m
```

This causes the backup to fail hard. Occaisionally it's a different file under Application Support but the result is the same as the backup fails.

**Comment by jkowalski** [comment]
Have you tried setting global or local policy to ignore errors ?

**Comment by cooperaj** [comment]
No, I will do that. But Ideally I'd want those files uploaded. Is the server getting registered with the correct permissions to work?

**Comment by jkowalski** [comment]
Server runs as the user account that started it.

**Comment by cooperaj** [comment]
Ah, in this case that will fail as the Containers folder runs outside of standard permissions. I do want to back it up though so will have to think about how to solve.

**Comment by jkowalski** [comment]
`sudo kopia snapshot create <path>` ?

**Comment by julio-lopez** [comment]
This probably requires enabling full-disk access for the Kopia app, probably for the server process.

For now, the simplest approach is to manually enable it via
_"System Preferences"_ => _"Security & Privacy"_ => _"Privacy"_ tab => _"Full Disk Access"_ (on the left list) => Add via the "`+`" sign and then select the kopia binary. I'm guessing the server binary, have not tried it yet.

**Comment by cooperaj** [comment]
> This probably requires enabling full-disk access for the Kopia app, probably for the server process.

Yeah, it doesn't work on the gui app. Where is the server binary?

**Comment by jkowalski** [comment]
GUI has server embedded in `/Applications/KopiaUI.app/Contents/Resources/server/kopia`

**Comment by cooperaj** [comment]
Using the information from here https://github.com/restic/restic/issues/2051 I've been unable to get this to work. I've added full disk access to both the KopiaUI and the server binary contained inside and I'm still getting permission denied errors when attempting to read from folders in ~/Library/Containers.

I'm not sure how to fix this.

**Comment by bbccdd** [comment]
Hi @cooperaj would you mind closing this ticket please? I'd like to do so but I don't know.

**Comment by cooperaj** [comment]
I'll take a look at if I ever figured this out. If not it's likely something that needs documenting on how to solve.

**Comment by bbccdd** [comment]
Thank you for your quick response.

Since your issue is about errors, not about backups of all folder contents you could look at this approach: ignore.

Example for global exclusion where you could also use the snapshot path.
```
root@host:~# kopia policy set --add-ignore "**/Library/Containers/com.apple.mail/Data/" --global
Setting policy for (global)
 - adding "**/Library/Containers/com.apple.mail/Data/" to "ignore rules"
```

Or edit manually like this:
`root@host:~# kopia policy edit --global`

and add
`  "files": {
    "ignore": [
      "**/Library/Containers/com.apple.mail/Data/",
`
Remove the comma if it is your last entry.

Does this work for you please @cooperaj ?

**Comment by cooperaj** [comment]
Well, yes, that would stop me from seeing errors when attempting to backup these locations.

The issue is that these locations are common across all macs using newer macOS versions and that since the workaround is to wrap application binaries so that appropriate macOS security policies can be applied it's probably something that needs documenting.

**Comment by bbccdd** [comment]
Indeed. I don't have a mac at my disposal right now.

Since Mac users will probably find this thread with a similar challenge in the future: what would you recommend? Perhaps you can share the notes on how to resolve this for others to benefit from.

**Comment by bbccdd** [comment]
Indeed we could have sticky post in the forum for using full disk access in macOS, common ignore rules per operating system and other good practices.

But, similar to why the issue was closed with restic, I belive this issue can be closed until Apple devices a better way to handle full disk access.

Folks looking for a workaround? Check out this post: https://github.com/restic/restic/issues/2051#issuecomment-834052994
`A3 to FDA -- Terminal.app, /usr/local/bin/bash, and /usr/local/Cellar/restic/0.9.2/bin/restic -- and now it ran without errors. 🤷‍♂️
`
