### ISSUE TITLE
Add MEGA.io to Supported Storage Locations

### ISSUE THREAD

**Issue by hl2guide** [kopia/kopia#3397]
Please consider adding **MEGA.io** and **MEGA.nz** to Supported Storage Locations.

[reference](https://kopia.io/docs/repositories/)

**Comment by basldfalksjdf** [comment]
Mega's object storage page says it is compatible with Amazon S3, so you should be able to use Kopia with Mega - but only Mega's object storage, not their regular storage. Use the Amazon S3 option in Kopia to do that.

Rclone may support Mega's regular storage, so you may be able to use Kopia's rclone integration, but that is not guaranteed to work.

**Comment by vaygr** [comment]
MEGA's object storage (also known as S4) is in beta and is not available (ETA is unknown).

I believe the issue is about MEGA cloud storage: https://mega.io/storage

There are a few open source clients that implement the protocol:

1. the official one at https://github.com/meganz/MEGAcmd
2. https://megatools.megous.com/
