### ISSUE TITLE
'kopia snapshot delete' not working as expected

### ISSUE THREAD

**Issue by rhd** [kopia/kopia#384]
Hi all, it's possible I'm doing this wrong...

```
root@Tower:~# kopia --version
0.5.2 build: 4f65495d811022e65d27e376e2d94f5b905d6c8c

root@Tower:~# kopia snapshot list
root@tower:/mnt/user/appdata
  2020-03-21 22:50:14 PDT k9051c78d7ef61e63afdaa0430999d85f 63.5 GB drwxrwxrwx files:299724 dirs:142241 (latest-2,hourly-2)
  2020-03-21 23:27:11 PDT ke77b5e20fe27beb190a8c1f70faf6ffb 63.4 GB drwxrwxrwx files:299719 dirs:142229 (latest-1,annual-1,monthly-1,weekly-1,daily-1,hourly-1)

root@Tower:~# kopia snapshot delete ke77b5e20fe27beb190a8c1f70faf6ffb --unsafe-ignore-source
kopia: error: not found, try --help
```

User error? Bug?

**Comment by jkowalski** [comment]
That's unfortunately confusing.

You need to do: `kopia snapshot list -m` to show manifest IDs and pass manifest ID instead of root object (`k***`).

Suggestions for improving the UX are welcome. The problem is that single root object `k` can be reused by multiple snapshots.

**Comment by rhd** [comment]
Ahh - the manifest. That does work.. thanks! It would be nice if the delete command recognized the root object (if possible) and told you to do the right thing.

Thanks for the great support. :+1:

**Comment by jkowalski** [comment]
sure, I think we can add deletion by root object and perhaps by time or range.

**Comment by julio-lopez** [comment]
> sure, I think we can add deletion by root object and perhaps by time or range.

The command is for _snapshot_ deletion, which are identified by their manifest ids. That's a well-defined API. Allowing deletions by root id as well becomes fuzzy, since more than one snapshot could point to the same root id.

If we allow specifying a root object, then it should be via a flag. But, there is still an issue of what the right semantics would be. Should all snapshots that point to that root id be deleted? only one, in that case, which one? and so on.
