### ISSUE TITLE
Document how to free up repository space?

### ISSUE THREAD

**Issue by jinks** [kopia/kopia#408]
I backed up something I didn't want to, now I'm trying to remove the data from the repo, but none of the commands actually free up any space.

I removed **all** snapshots from the relevant directory, so it doesn't show up in snap ls any more.

What I tried so far:
`kopia snap gc --min-age=1s --delete`
`kopia snap verify --all-sources --verify-files-percent=100`
`kopia blob gc --delete=yes --min-age=1s`

Repo size before and after is identical.

Output from kopia snap gc:
```
19:02:16.687 [kopia/snapshot/gc] looking for active contents
19:02:16.688 [kopia/upload] processed(0/11) active 1
19:02:16.943 [kopia/snapshot/gc] looking for unreferenced contents
19:02:16.967 [kopia/snapshot/gc] found 0 unused contents (0 B bytes)
19:02:16.967 [kopia/snapshot/gc] found 0 unused contents that are too recent to delete (0 B bytes)
19:02:16.967 [kopia/snapshot/gc] found 17901 in-use contents (4.3 GiB bytes)
19:02:16.967 [kopia/snapshot/gc] found 13 in-use system-contents (7.1 KiB bytes)
```

Output from kopia blob stats:
```
Count: 391
Total: 8.1 GB
Average: 20.7 MB
Histogram:

        0 between 0 B and 10 B (total 0 B)
        0 between 10 B and 100 B (total 0 B)
        1 between 100 B and 1 KB (total 681 B)
       14 between 1 KB and 10 KB (total 60.3 KB)
        6 between 10 KB and 100 KB (total 235.1 KB)
       11 between 100 KB and 1 MB (total 5.9 MB)
        8 between 1 MB and 10 MB (total 32.7 MB)
      351 between 10 MB and 100 MB (total 8 GB)
```

Output from kopia blob gc:
```
Looking for unreferenced blobs...
Found 0 blobs to delete (0 B)
Deleted total 0 unreferenced blobs (0 B)
```

Kopia version is 0.5.2 release, repo created with 0.5.0.
What am I missing? Why is snap reporting 4.3GB in use and blob 8GB?

**Comment by jkowalski** [comment]
Fully automated cleanup is a pending work item for 0.6 or 0.7 release. In the meantime, you can use low-level garbage collection tools:

* `kopia snap gc --min-age=1s --delete` - marks all contents not reachable by any snapshots as deleted
* `kopia index optimize --skip-deleted-older-than=1h --all` - remove old deleted entries from indexes
* `kopia content rewrite --short` - creates new blobs which contain only live contents (this makes old blobs candicates for Blob GC)
* `kopia blob gc --delete=yes --min-age=1s` - deleted unreferenced blobs

**Comment by jinks** [comment]
Neat.

The content rewrite was the one I missed.
Thanks.

**Comment by jkowalski** [comment]
Repurposing this issue to track adding this to the documentation/website.

**Comment by aksdb** [comment]
Will this feature consider storage provider restrictions? For example in B2 it is expansive to download stuff. So if GC means downloading nearly everything, rewriting and and reuploading it, it could end up being a not-so-nice surprise getting the bill for that.

Sure, some download/rewrite/upload cycles are necessary, but is the data structured in a way that this will most likely only affect small portions of the stored files or is it more likely that every single blob will have to be touched?

**Comment by jkowalski** [comment]
What a great question.

What happens every time Kopia makes a snapshot is it writes a number fo new `n`, `p` and `q` blobs to the repository (index, data and metadata respectively). It never updates any blobs that were written before, but it will sometimes delete ones that are no longer needed.

Normally Kopia tries to keep blobs packed for efficiency (ideally making each blob >20MB in size). Sometimes (or most of the time) when you make small differential backups the blobs saved are really small (because there wasn't much to save to begin with) and very quickly you end up with hundreds of small blobs which will slow down listing, etc. So it makes sense to get rid of the small ones periodically for best performance.

Also, sometimes when you delete stuff, a previously written blob that is >20 MB really only has 5 KB of live data left, so it makes sense to get rid of it and replace with a 5MB blob to save space.

Kopia does (not automatically at the moment, but will become so) perform compaction where it iterates through indexes to find which blobs are below 80% of their desired size (20 MB) and rewrites all of those together into new blobs which are big and don't have any dead contents in them.

There are 2 types of data blobs: `q` which holds directory listings & manifests which are generally small and can be re-written more aggressively (say every few hours) and `p` which hold data (which will be compacted every few days to weeks). This is generally a very quick process and downloads only short files and re-uploads much bigger files which will not need to be rewritten again (that is until you delete something significant).

Note that this never really touches blobs that are above 80% of their 20MB target and never change, so if you don't delete much, I think you can be confident that the rate of downloads and re-uploads should be reasonable.

Btw there is #411 in flight which adds `kopia gc --quick` and `kopia gc` convenience commands that will perform all maintenance automatically.

There will be some flags to control the frequency aggressiveness of the rewrites, so it should be possible to tune it to optimize cloud cost vs performance.

**Comment by aksdb** [comment]
Thank you for that thorough answer!

Wow, that concept is really well thought through. That definitely enforces the confidence I need to have in a backup tool. Thank you so much for all your work and again for that very very good detailed answer to my question :-)

**Comment by tetsumaki** [comment]
Hello,
Is it possible to delete all the snapshots and recover all the space ?
I tried that but it's not work :

````text
$ kopia snap gc --min-age=1s --delete
$ kopia index optimize --skip-deleted-older-than=1s --all
$ kopia content rewrite --short
$ kopia blob gc --delete=yes --min-age=1s
````

kopia is my repository directory :

````text
$ du -sh kopia/
2.1G    kopia/
$ ls -R kopia/ | wc -l
695
````

**Comment by jkowalski** [comment]
In recent builds you can do `kopia gc --full` which should take care of full cleanup. Note that it will not delete most recently mutated objects (for safety reasons), only objects older than 2h.

**Comment by jkowalski** [comment]
This is now documented on https://kopia.io/docs/maintenance/
