### ISSUE TITLE
Programmatic API

### ISSUE THREAD

**Issue by tigerwill90** [kopia/kopia#417]
Hi,

First of all, thank's for this very promising tool !

I [read](https://kopia.io/docs/reference/go-api/) you provide an API for accessing repository. There is also a **snapshot API** outside of `internal` directory and I have already made [some test](https://github.com/tigerwill90/kopia-plugin-test) based on kopia implementation. I plan to integrate kopia in a open source backup orchestrator tool for database. Is there any reason I shouldn't use the snapshot package ? Did you plan big change in the structure of the project ?

Thank's in advance, stay safe.

**Comment by jkowalski** [comment]
Repository is a general purpose content addressable storage. Snapshot, Policy and FS are strictly a layer on top of that. 

Both are meant to be consumed as API, just be aware that before 1.0 the API may undergo slight changes.

**Comment by tigerwill90** [comment]
it's good to know, thank's !

**Comment by jkowalski** [comment]
BTW improvements to the API in the form of PRs are more than welcome.

**Comment by flibustenet** [comment]
@jkowalski will it make sense for you to separate layers in separate projects ? It can help us to follow a change in API. Also we can imagine that in the futur the UI will change but not the repository part. Maybe it's too early to think about that.

**Comment by jkowalski** [comment]
I actually had repo layer in separate project for a while but merged them for simplicity . I think it will make sense to separate again before 1.0 but not now since the API is still being tweaked. 

Note that repo layer does not really deal with the file system concepts (snapshots, policies) but is a lower level that implements generic content addressable storage.
