### ISSUE TITLE
how to delete a snapshot ?

### ISSUE THREAD

**Issue by kuyagic** [kopia/kopia#435]
I use the following command to delete a snapshot
```
root@zmbox:/opt/config/kopia# kopia snapshot delete kddb8afc3321307a2bfafbc83704b019c
kopia: error: path is required, try --help
```
which the cmd
```
root@zmbox:/opt/config/kopia# kopia snapshot list /etc/dnsmasq.d
root@zmbox:/etc/dnsmasq.d
  2020-05-06 20:04:34 CST k52a5cf59b6733efc9c8c677dd78805e0 5.8 MB drwxr-xr-x files:10 dirs:2 (latest-4)
  + 1 identical snapshots until 2020-05-06 20:33:56 CST
  2020-05-06 20:37:28 CST kddb8afc3321307a2bfafbc83704b019c 5.8 MB drwxr-xr-x files:9 dirs:1 (latest-2)
  2020-05-06 20:38:49 CST kd73d7a27e46e5764101513ee844a5129 5.8 MB drwxr-xr-x files:10 dirs:2 (latest-1,annual-1,monthly-1,weekly-1,daily-1,hourly-1)
```
shows the id is correct

the version I use is below
```
root@zmbox:/opt/config/kopia# kopia --version
0.5.2 build: 4f65495d811022e65d27e376e2d94f5b905d6c8c
```

**Comment by jkowalski** [comment]
Yeah. This is confusing and I think we should change the behavior so that it matches user expectations. 

The identifiers starting with ‘k’ are object ids that can be shared by multiple snapshots and they don’t uniquely identify a single snapshot. 

To delete snapshot  you need to (currently) pass manifest id which can be displayed by passing -m to snapshot list command. 

I think Kopia can be smart and accept either format and sometimes delete more than one snapshot.
