### ISSUE TITLE
May never complete snapshot of a large file

### ISSUE THREAD

**Issue by redgoat650** [kopia/kopia#463]
An issue may have emerged with checkpoints (https://github.com/kopia/kopia/pull/410), where if a snapshot is taking place of a single large file (tested at 500 GiB), the checkpoint behavior can kick in, restarting the snapshot and therefore restarting the read of the large file. This can lead to an infinite repeat of partially reading through the file and then restarting.

In testing, Kopia ran `snapshot create` on a 500G file continuously for more than 19 hours, and had to be terminated manually. The logs indicated checkpoint functionality was being invoked periodically, after about 130 GiB was read each time.

**Comment by jkowalski** [comment]
That's a very interesting. I would expect >=2nd attempt to spend time on reading the file and hashing because uploads are not required.

Checkpointing is done after 45 minutes (or at least it should), that means we're getting throughput of about 2.8 GB/minute or only ~48 MB/second. It looks pretty terrible (single-threaded hashing + default encryption should be >500 MB/sec, I'm assuming file I/O can do more than 48 MB/second.

Do you have any idea what is being slow?

**Comment by ntolia** [comment]
@jkowalski This isn't that slow on clod providers where I/O is based on instance and disk size or on older on-prem arrays. Look at https://cloud.google.com/compute/docs/disks/performance and what one would get for a 500GB standard persistent disk (theoretical max is 60 MB/s).

**Comment by budachst** [comment]
I am experiencing this issue, even with smaller files. My test setup currently tries to backup approx. 8TB of data from a Ceph FS, which holds the backups of a lot of KVM virtual disks. It somewhere progresses up the point where the biggest file to backup has reached 35GB+ and as of then, it simply won't progress further, but enter the described loop.

From what I gathered, the speed of the underlyng rack is pretty good, approx. 380 MB/s. Given the fact, that the largest file is 286GB and the read speed vary from 135MB/s at 4k reads up to 360MB/s for 1m reads, the speed of the underlying storage should not be an issue. Even at 135 MB7s, the time to read the largest file should be well below the 45 min. checkpoint interval.
