### ISSUE TITLE
Cannot run garbage collection

### ISSUE THREAD

**Issue by aksdb** [kopia/kopia#503]
I am trying Kopia 0.6-rc1.
I open a repository created with Kopia 0.5.2. When I run `gc` (which has to be done manually now if I understood correctly?) it ends up with:

```
kopia --config-file=kopia.config gc
kopia: error: maintenance must be run by designated user: , try --help
```
`kopia gc --help` doesn't say anything about "user" or even about "gc".

**Comment by jkowalski** [comment]
What a great bug!

Here's what happened:

In Kopia 0.6 we are introducing dedicated maintenance tasks that perform various cleanups and compactions of the repository. In most cases those are safe to run by any user at any time, but there are some that must run in a critical section or that rely on particular timings for correctness.

To facilitate this, Kopia requires that one user@host be designated as the owner of maintenance activities. By default this is the user that creates the repository, but since you migrated from 0.5.2 this setting was never set.

You can see the designated owner and see the status, timings and other parameters of maintenance operations using `kopia maintenance info` command (`kopia gc` is an alias for `kopia maintenance`)

```
$ kopia maintenance info
Owner: root@master
Quick Cycle:
  scheduled: true
  interval: 1h0m0s
  next run: 2020-07-27 22:43:19 PDT (in 4h17m48s)
Full Cycle:
  scheduled: true
  interval: 4h0m0s
  next run: 2020-07-27 21:43:19 PDT (in 3h17m48s)
Recent Maintenance Runs:
  full-delete-blobs:
    2020-07-27 17:44:57 PDT (2s) SUCCESS
    2020-07-27 13:23:53 PDT (2s) SUCCESS
    2020-07-27 08:45:04 PDT (2s) SUCCESS
    2020-07-27 04:24:12 PDT (2s) SUCCESS
    2020-07-26 23:45:19 PDT (2s) SUCCESS
  full-drop-deleted-content:
    2020-07-27 17:44:37 PDT (14s) SUCCESS
    2020-07-27 13:23:33 PDT (14s) SUCCESS
    2020-07-27 08:44:40 PDT (16s) SUCCESS
    2020-07-27 04:23:35 PDT (30s) SUCCESS
    2020-07-26 23:44:41 PDT (31s) SUCCESS
  full-rewrite-contents:
    2020-07-27 17:44:52 PDT (5s) SUCCESS
    2020-07-27 13:23:48 PDT (4s) SUCCESS
    2020-07-27 08:44:57 PDT (7s) SUCCESS
    2020-07-27 04:24:06 PDT (6s) SUCCESS
    2020-07-26 23:45:12 PDT (6s) SUCCESS
  snapshot-gc:
    2020-07-27 17:43:19 PDT (1m17s) SUCCESS
    2020-07-27 13:22:18 PDT (1m15s) SUCCESS
    2020-07-27 08:43:19 PDT (1m21s) SUCCESS
    2020-07-27 04:22:21 PDT (1m13s) SUCCESS
    2020-07-26 23:43:23 PDT (1m17s) SUCCESS

```

You can can configure the owner with:

```
$ kopia maintenance set --owner=USER@HOST
```

or to quickly assign current user as the owner:

```
$ kopia maintenance set --owner=me
```

You can use other flags of `kopia maintenance set` to configure things like maintenance task interval, enable/disable or pause until specified time.

The only caveat with maintenance tasks is that if a user has been designated to own maintenance, they must periodically use kopia which will trigger maintenance automatically - if they don't, the repository will not be cleaned up or compacted, which may lead to bad performance (Kopia should be displaying warning when this happens).

Having said all that, this is a very new mechanism, I'm looking to tweak it to be user friendly and as unobtrusive as possible before we release 0.6 and make sure migration from 0.5.2 to 0.6 is smooth. Thanks again for the report!

**Comment by jkowalski** [comment]
BTW, you can trigger maintenance manually with:

```
# quick maintenance
$ kopia maintenance 

# full maintenance
$ kopia maintenance --full
```

**Comment by aksdb** [comment]
> The only caveat with maintenance tasks is that if a user has been designated to own maintenance, they must periodically use kopia which will trigger maintenance automatically - if they don't, the repository will not be cleaned up or compacted, which may lead to bad performance (Kopia should be displaying warning when this happens).

No I am a bit confused. In the changelog it says:

> * introduced explicit maintenance operations that perform periodic repository cleanup/compaction (#411)
* disabled automatic compaction on repository opening - moved to maintenance tasks

... which implies, that maintenance tasks are now no longer performed automatically. So I would always have to perform `kopia maintenance` explicitly from time to time. At least that's what I read from it :-)

If maintenance is still performed automatically from time to time, then how about the following:

* The owner is used to designate, who is responsible for automatic maintenance (as you stated).
  * The setting can then be used to change or adjust that at any time.
* However an explicit maintenance run can be invoked by anyone without changing the owner (I guess it should still be possible to acquire a temporary lock to prevent other backups or maintenance runs from interfering).

---

Anyway, thank you very much for your detailed explanations! That is awesome documentation right there (although I hope it will be part of the central/official documentation too, since this is knowledge that should not get lost in a closed github ticket :-))

**Comment by jkowalski** [comment]
This should be documented in https://kopia.io/docs/maintenance/ Closing this issue.
