### ISSUE TITLE
question: large directories and repositories

### ISSUE THREAD

**Issue by shtratos** [kopia/kopia#504]
I appreciate your work on a scalable open source backup solution. Working with Restic I encountered several scalability issues. I imagine you might have encountered them already. 

how do you deal with the following scenarios:
- a directory with millions of small files
- a repository with billions of blocks

In Restic both of these scenarios result in unbounded memory consumption. 

Large directory becomes a problem because it's manifest is stored in one blob. constructing the manifest, serialising it as JSON and then encrypting takes a lot of RAM. Do you split manifest of large directories in pages?

As a repository grows in size with time,number of block ids also grows. When you check if a particular block is in the repository you need to check its id against block ids index. Where is that index stored? If it's in memory, then backing up requires amount of RAM proportional to the number of blocks in the repository. This becomes a problem when you want to backup low resource machines.

**Comment by jkowalski** [comment]
Kopia should in theory work with very large repositories, folks at Kasten have done some performance tests and you should see performance numbers out around 0.6 release timeframe.

To answer your questions: Each directory entry is currently stored in JSON format similar to:

```{"name":"format_block_test.go","type":"f","mode":"0644","size":2742,"mtime":"2020-05-13T07:52:22.994864815-07:00","uid":501,"gid":20,"obj":"3e13b73b4ff97713b9aa1710510e480a"}```

This consumes about <200 bytes per entry uncompressed, but can be compressed to about 25% with simple gzip. Today kopia does not enable compression of directory listings (only file contents are compressed), but that's trivial to add in future versions.

Directory listings need to be sorted to ensure consistent hashing, so the listing has to be held in memory at some point. 1M of files would be O(200MB) of data in RAM, so that will be stressing memory as you mentioned during large processing. 

There are things that could be done here (in the future), including sharding where a single directory is stored as N interleaved listings (based on their filename hashes) that are merged together on read. This would mean processing a directory is done N times during upload, but memory usage would drop by a factor of N. We could use policies to enable sharding for very large directories or do it automatically based on some count threshold. All ideas for future versions.

When it comes to storing large directory listings, they will be automatically split into chunks of roughly ~4MB and individually saved to repository followed by an index content that links them together. This is done today and you may sometimes see directory objects represented by I-prefixed names, such as `Ika8a0eb1d516c1fbf3894a5980122975d`.

AFAIK repositories with billions of contents has not been tried before and will likely be slow, but will not need RAM to hold all index entries. 

Kopia does store index blobs (prefixed with `n`) in large chunks and does periodic compaction. Index blobs are stored in a format that allows them to be mmap()-ed and merged without parsing, and overhead for very large repositories should be O(number-of-index-blobs) not O(number of entries in index blobs). When looking for a particular content in the index kopia does binary search across all index blobs and merges the results, without having to load the indexes into memory. Compaction should take care of keeping  number of index blobs in check, but there are likely limitations and bugs we've not encountered yet, simply because nobody tried this scale.

Index blobs use tight binary packing of ~21 bytes+len(ID) per entry, so that for 128-bit hashes gives 37 bytes/entry and for 256-bit hashes gives 53 bytes/entry.

Having said that, there are some operations during GC that require buffering large amounts of data in RAM to determine what is alive in the repository vs what can be collected- the scalability of that has not been determined yet, but I would imagine significant memory pressure for very large repositories.

To give you a sense of how repository scales for common usage, here are the stats of my personal repo:

```
# statistics at the content level, also measuring time to merge and parse through all index entries
$ time kopia content stats
Count: 988850
Total: 589.5 GB
Average: 596.1 KB
Histogram:

        0 between 0 B and 10 B (total 0 B)
    76102 between 10 B and 100 B (total 3.8 MB)
   373595 between 100 B and 1 KB (total 159.1 MB)
   207665 between 1 KB and 10 KB (total 663.5 MB)
    58643 between 10 KB and 100 KB (total 1.8 GB)
    58222 between 100 KB and 1 MB (total 28.4 GB)
   214623 between 1 MB and 10 MB (total 558.4 GB)
        0 between 10 MB and 100 MB (total 0 B)

kopia content stats  1.74s user 0.50s system 155% cpu 1.436 total

# statistics of physical files stored in the S3 bucket:
$ kopia blob stats
Count: 26820
Total: 593.6 GB
Average: 22.1 MB
Histogram:

        0 between 0 B and 10 B (total 0 B)
        0 between 10 B and 100 B (total 0 B)
      372 between 100 B and 1 KB (total 60.1 KB)
      109 between 1 KB and 10 KB (total 425.3 KB)
        6 between 10 KB and 100 KB (total 290 KB)
       20 between 100 KB and 1 MB (total 4.8 MB)
        2 between 1 MB and 10 MB (total 15.4 MB)
    26311 between 10 MB and 100 MB (total 593.6 GB)

```

**Comment by jkowalski** [comment]
Closing - if you have additional questions, please use the new Kopia Forum http://kopia.discourse.group
