### ISSUE TITLE
Package for Arch Linux

### ISSUE THREAD

**Issue by jkowalski** [kopia/kopia#582]
As requested in https://kopia.discourse.group/t/archlinux-package/65

**Comment by githubuser0000000001** [comment]
This is an AUR PKGBUILD file version that seems do the job for the kopia CLI version (using make install).  I imagine the other versions could be included within as options but I haven't got that far as the CLI version is all I'm currently using.

It works well for me when tested on my local machine, but I haven't yet tried to make an upload to the AUR yet.
I would appreciate feedback on the dependencies as I'm not sure they are complete.  I will do some more investigating.  I currently have 'go>=1.14' and 'git' as dependencies.  Are there others I should include?
Reference:
https://wiki.archlinux.org/index.php/PKGBUILD
https://wiki.archlinux.org/index.php/VCS_package_guidelines
https://wiki.archlinux.org/index.php/Arch_Packaging_Standards
https://wiki.archlinux.org/index.php/Namcap
https://wiki.archlinux.org/index.php/.SRCINFO

[PKGBUILD.zip](https://github.com/kopia/kopia/files/5166315/PKGBUILD.zip)

**Comment by githubuser0000000001** [comment]
This is an AUR PKGBUILD file version that seems do the job for the kopia CLI version (using make install). I expect it could be expanded to include AUR "split" packages that might given the user an option to install the other packages provided by kopia.

It works well for me when tested on my local machine.  I haven't yet made an upload to the AUR.

I would appreciate feedback on the dependencies as I'm not sure they are complete. I currently have 'go>=1.14' and 'git' as make dependencies. Are there others?  I don't believe there are any run-time dependencies.

Because of the layout of the Github repo there are options on what the user can install.  In this case I had to choose between the master, 0.6-hotfixes or the <https://github.com/kopia/kopia/releases/download/v0.6.4/kopia-0.6.4-linux-x64.tar.gz> download binary file.  This PKGBUILD currently is set to install the 0.6-hotfix.  Either using that or the master make for an easier build as the checksums are not used, as they are required for the tar.gz file.  I believe the installation of the tar.gz file requires manual input to the PKGBUILD file to select the file version as it changes.

When the branch is moved back to the master then this will need to be updated in the PKGBUILD file.

The PKGBUILD file can be used locally for a user that has `pacman` and other dependencies installed, or uploaded (ideally) to the AUR.

Selected References:
https://wiki.archlinux.org/index.php/PKGBUILD
https://wiki.archlinux.org/index.php/VCS_package_guidelines
https://wiki.archlinux.org/index.php/Arch_Packaging_Standards
https://wiki.archlinux.org/index.php/Creating_packages

[PKGBUILD.zip](https://github.com/kopia/kopia/files/5173418/PKGBUILD.zip)

**Comment by GraphZal** [comment]
I've created a PKGBUILD for v0.7.3. Since the AUR only holds "build recipes", there is no modification of the centralized build process needed. I'll just go ahead and upload and maintain the PKGBUILD on the AUR, unless you have objections.  

That said, it would be nice to have one of the following three things, in order to provide more security for the build:
- a signature and checksum on the source-code tarball
- or a signature on the git tag
- or a signature on the git commit that the tag points to (by a proper key you control, like the key used to sign the other packages and checksums, not the GitHub controlled key used automatically by GitHub when working on the web interface)


[PKGBUILD.txt](https://github.com/kopia/kopia/files/5403105/PKGBUILD.txt)
(.txt extension added because GitHub complains otherwise. Remove it for use)     
So far, it's only the command-line version, as I've not yet managed to build a fully functional UI version from the source code.

**Comment by githubuser0000000001** [comment]
Thanks.  You've done a better job at it than I was able to using the release source and seem to have a better understanding of the process.  Hopefully a signature and checksum for the source will be included in the listing in future.

I'm primarily interested in the CLI version but I'm sure there might be others that would use the UI version.

**Comment by dhopfm** [comment]
Thanks for your work, @GraphZal !
> So far, it's only the command-line version, as I've not yet managed to build a fully functional UI version from the source code.

While I think it would make sense to have a separate package for the fat client UI it would be great to have the built-in web UI available with the CLI which currently isn't the case. Replacing `go build` by:
```
make html-ui-bindata
go build -tags embedhtml
```
did work for me.

**Comment by GraphZal** [comment]
That's a good idea, @dhopfm. 
Thanks for finding the right build commands.

I'll test it and amend the pkgbuild accordingly as soon as I have time. Probably at some point later this week.

**Comment by GraphZal** [comment]
I can now confirm the "patch" by @dhopfm seems to work fine. 

However, I will hold off on integrating it into the pkgbuild until #698 is either resolved or someone convinces me that it's safe anyway.
