### ISSUE TITLE
Command to backup an explicit list of files only (not directories) - and nothing more?

### ISSUE THREAD

**Issue by hi2u** [kopia/kopia#680]
The normal usage of Kopia is to back up whole folders, like this:

```
kopia snapshot /foldername/
```
(and you can possibly use some kind of exclude file/pattern list to tell it what to ignore)

Is there instead a different command (or method) where I can basically do the opposite?  i.e. simply pass in a list of the files that I want backed up, and only those files are backed up?

e.g. let's say I've used `/usr/bin/find` (or any other more complicated/manual method) to create a file list based on some complicated include/exclude rules: `/tmp/my-file-list.txt`... just a plain .txt file of full filepaths...

```
/foldername/this-should-be-backed-up.jpg
/foldername/and-also-this-one.doc
```

I'm imagining some kind of command where the only source(s) argument is the name of the filelist:

```
kopia.exe snapshot --from-filelist=/tmp/my-file-list.txt
```

Kopia would then backup just those 2 files, and nothing more.  

(although in reality the file lists will contain many 1000s of files, too many to specify as command line arguments)

As an example, Restic supports this using the flag `--files-from`: https://restic.readthedocs.io/en/latest/040_backup.html#including-files - so I'm wondering if I can do the same with Kopia?

**Comment by dimitarvp** [comment]
I second this. I lately wanted to thin my backups because I sync to 7 cloud services on free accounts and most are capped at 5GB. Being able to include/exclude files/dirs would be extremely valuable. I only backup code and some of the data it uses (JSON / CSV / SQL files). So far I've used `kopia` to blindly snapshot build artifacts but I am putting an end to it.

I have successfully completed this home-grown solution:

- Use the Rust tool `fd-find` -- which applies `.gitignore` rules in the dir if it exists -- plus globally excluded files/dirs (like macOS' `.DS_Store`).
- Feed `rsync`  the resulting explicit files/dirs list to make a smaller copy of all the files/dirs I want backed up with `kopia`.
- `rsync` fills up a staging area dir only with that explicit files/dir list.
-  `kopia` then snapshots that staging area directory.

It works and my backups became ~2x smaller but it seems hacky, plus gathering the complete list of files and feeding it to `rsync` takes ~90s on a machine with an extremely fast SSD so even such an amazingly fast program like `fd` is struggling; I can further improve my script and can likely speed it up but again, it seems hacky.

A first class support for inclusions/exclusions in `kopia` would be ideal.

**Comment by julio-lopez** [comment]
Currently

- kopia supports inclusion / exclusion via policies
- kopia allows specifying a specific file as a snapshot source

**Comment by mitchellroe** [comment]
In case anyone else has come here looking for a solution, I have found a workaround that seems to work well enough.

In the ignore list, I start with `/*`, then add each item that I **do** want backed up with a `!` preceding it.

```
/*
!/Documents
!/Games
!/.ssh
```

If there are sub-directories in those that I still want ignored, I just just add those in as explicit ignores.

```
/*
!/Documents
/Documents/code
!/Games
!/.ssh
```
