### ISSUE TITLE
[Feature] stdin support

### ISSUE THREAD

**Issue by bbigras** [kopia/kopia#683]
Use case:
**A hosting provider only allows me to make backup as `.tar.gz` files. I would like to feed those directly to Kopia.**

With Restic I can do `gunzip -c backup.tar.gz | restic -r ~/repo backup --stdin` which is pretty simple.

> We should start by filing an issue to discuss the exact usage, since it cannot be that simple unfortunately (we need to keep track of these snapshots somehow and in Kopia snapshots are identified by user@host:path)

source: https://kopia.slack.com/archives/CH7R8L2KD/p1602654316115900

No idea if it could help but Restic allows to set a timestamp and filename like this:
`restic backup --stdin --time "2020-01-08 12:00:00" --stdin-filename backup.tar.gz`

**Comment by saviodsouza** [comment]
At the moment it's not supported

There is a forum thread about the same
[Form](https://kopia.discourse.group/t/backup-standard-input/161)

**Comment by eras** [comment]
Yes, this would be great!

With Ceph it would be possible to backup rbd snapshots with `rbd export images/host-root@snapshot | kopia snapshot --stdin=/rbd/images/host-root` (restic syntax seems applicable) and it would probably be just as nice as direct support for rbd.

Currently the only way to go is to have a large temporary directory—not to mention the name of directory is silly (in my case `/mnt/tmp`), because the files are only visiting the filesystem.

**Comment by jkowalski** [comment]
I'm marking this as `help wanted`, because I think this would be a good small feature to implement by an external contributor - also a good learning opportunity since the feature will cut through several layers of Kopia.

**Comment by julio-lopez** [comment]
An initial implementation for this feature should be relatively simple. The minor hurdles are around ensuring that the feature works well with some of the existing user expectations and the associated details of the user experience, such as the specific command line flags, their meanings, etc.

Let's simplify and clarify the _minimum_ requirements and call out or separate optional or other desired features. 

1. The input is an opaque blob, initially, assume just a stream of bytes.
2. Support for input via `stdin` from an external process or a some redirection which is external to `kopia`. That is, `kopia` is NOT launching the external process, or connecting to a socket, etc. That is out of scope. We can consider other forms of specifying the data source later.
3. A successful execution should create a _snapshot_ associated with a _kopia source_ , so other features such as restore, mount via fuse, retention policies, etc. work as expected. This probably means that the resulting object needs to have a "file name" as well.
4. (optional) the ability to specify a _"directory path"_ for the resulting file.
5. It should work well, that is, it should not break the `snapshot create --all` command (as Jarek pointed out).

Let's discuss a couple of simple proposals for addressing (3) and (5) above.

cc: @pavannd1

**Comment by bbigras** [comment]
Maybe also note of this restic feature request https://github.com/restic/restic/issues/2226

**Comment by julio-lopez** [comment]
@bbigras That makes sense. However, it also makes sense to initially constraint the scope to implement the basic functionality to read the input from `stdin`.

As noted above, in particular point (1), the initial objective is to only support opaque byte streams. Once that is implemented, we can look into potentially parsing `tar` streams. That has its own set of additional quirks given the way kopia currently builds the file system hierarchy for a snapshot. It does not make sense to block implementing the basic functionality until all of those are ironed out.

**Comment by jkowalski** [comment]
I agree Julio's comments in https://github.com/kopia/kopia/issues/683#issuecomment-738469182 and that we should start simple and support backing up a single file from stdin as the first step.

For 5) I think there should be a way to mark snapshots or  as "manually managed", where they are never subject to deletion and are excluded from "snapshot create --all". Not sure if this should be one or two flags, but something to that affect.

Later on we could indeed do TAR parsing (although due to sequential nature of TAR this would be very different code than current uploader which is massively parallelized).

I've also been thinking about support for before/after hooks, and I also came up with the following idea, which may be helpful here. Wondering what your thoughts are:

We could add a policy (per folder, user, host or global) that designates some scripts as "data scripts" and Kopia would run those scripts and automatically upload their stdout.

For example:

`kopia policy set --global --data-script-suffix='.kopia-backup.sh`

Now say you have a directory with 3 scripts:

/mybackups/foo.kopia-backup.sh
/mybackups/bar.kopia-backup.sh
/mybackups/baz.kopia-backup.sh

When you snapshot `/mybackups` that, Kopia would invoke each script (because their name matches the suffix) and upload their stdout contents (in addition to scripts themselves):

/mybackups/foo.kopia-backup.sh
/mybackups/bar.kopia-backup.sh
/mybackups/baz.kopia-backup.sh
/mybackups/foo (stdout of foo.kopia-backup.sh)
/mybackups/bar (stdout of bar.kopia-backup.sh)
/mybackups/baz (stdout of baz.kopia-backup.sh)

Now if I have 10 MySQL databases to backup, I can create 10 scripts with `mysqldump` each and voila, Kopia takes care of running those for me each time we create snapshots.

What do you think, is that too much?

**Comment by julio-lopez** [comment]
Jarek, regarding the scripts, yes, that's also a good idea. Again, in the interest of initially keeping it simple, we can iterate afterwards. Filed #708 and #709 for tracking those.

**Comment by julio-lopez** [comment]
The first thing that we should define is how to represent "special" snapshot sources that should be excluded from `snapshot create --all`. Among others, a couple of options include:
* Making it a property of the source, that is extending the source tuple `(user, host, path)` to also include additional information.
* Supporting different types of snapshot manifests and making them extensible.

These two are not necessarily exclusive from each other.
Any other options / thoughts? @jkowalski @pavannd1

**Comment by jkowalski** [comment]
I prefer the first option, but we need to figure out how to set that property on the source. Currently it can only be done via policies. Alternatively we store it on the snapshot itself.

**Comment by julio-lopez** [comment]
> I prefer the first option, but we need to figure out how to set that property on the source. Currently it can only be done via policies.

Policies seems like a good mechanism. It has the (probably desired) side effect of being able to exclude specific sources from `create --all` even if the source was a "regular" FS snapshot.

> Alternatively we store it on the snapshot itself.

This means adding a marker or some additional data to the snapshot manifest struct, right?

**Comment by pavannd1** [comment]
It was straight forward to get `stdin` working by adding support for virtual sources. Currently exploring the policies part to add some additional information about these sources.

**Comment by jkowalski** [comment]
Basic stdin streams support is now in, closing this issue. We can create separate FR for improvements including data scripts.
