### ISSUE TITLE
Ransomware question

### ISSUE THREAD

**Issue by jon-durand** [kopia/kopia#743]
Hello, I hope it's alright if I ask a question here. I am a noobie learning about backup software for the first time and trying to choose one to use with cloud providers like Backblaze. I wanted to understand better how a certain scenario would play out. 

If I use Kopia to backup all the files on a computer hard drive to a Backblaze B2 bucket, I understand first backup copies everything, subsequent copies are incremental only adding changes. If ransomware encrypted or messed with a large portion or all the files on my local storage drive, and an automated Kopia backup script ran another backup what would the ransomware attacked files look like going to B2? Would it just look like a large change had happened, and I could still mount my cloud storage and download my files based on a previous daily restore point?

Thank you for your time, trying to understand how this stuff works but it's new to me.

**Comment by jkowalski** [comment]
Assuming the attacker does not destroy Kopia repository in the cloud, full restore should be possible. 

I'm not really familiar with ransomware attacks and how they work, but I would imagine one of few things could happen:

1. Kopia configuration files get encrypted by ransomware and are no longer readable - Kopia will not be able to make any more snapshots. This is actually good because it prevents garbage from being uploaded.

2. Kopia.exe is encrypted and will not run, basically same as 1

3. Regular files are encrypted but not Kopia nor its configs, - Kopia will basically reupload everything again (large amounts of garbage that can't be decrypted), but previous retained snapshots are unaffected and can be restored.

Also we recently started looking into leveraging cloud-level features offered by certain clouds such as locking and versioning that could be used to protect the repository even if ransomware decides to maliciously destroy or clobber it. 

@julio-lopez

**Comment by jon-durand** [comment]
Thank you jkowalski!

Regarding the cloud level features you mentioned, I do remember reading about terms like immutability, and append only, where anything previously backed up is read only and only new things can be added to the cloud. I wasn't sure if when Kopia adds incremental data to a backup if it for sure didn't need to edit any previously existing file and only new files were added to the repo. 

My fear was that I could potentially enable a append only setting on the cloud providers end, and then when trying to run a subsequent backup if a require operation by Kopia would be blocked in the case that it did need to edit a previous existing file to add the increment.

**Comment by julio-lopez** [comment]
High level bits:

Kopia creates new blobs for backups, it does not modify previous ones.

Kopia does not yet support _write-once read-many_ (WORM) features supported by various object stores. For instance, see #711. We are looking into adding basic support for those.

**Comment by jon-durand** [comment]
Thank you both for helping so quickly with my question. 
I don't think I have any more questions. I've decided to use Kopia as my backup and watch out for any new features related to WORM as they come out.
