### ISSUE TITLE
[Question] A few noobie questions

### ISSUE THREAD

**Issue by jon-durand** [kopia/kopia#750]
Hello, hope it's okay to ask more noobie questions. 

- If I upload something with compression and later decide to remove compression from the snapshot policy and keep making the routine scheduled snapshots will that mess anything up? What if I interrupt a snapshot half way and change the policy from compression to no compression, it will be able to figure things out?

- If I use 'kopia snapshot remove snapshot-id' that is equivalent to deleting all the data for that snapshot from my cloud storage correct? If there are policies like 'keep snapshot for 5 days' that removal won't stick around for 5 days because it was an explicit removal?

- Currently I was using global policy to set the scheduled upload of a bunch of folders since I wanted them all to have the same schedule. But if I ever want to upload a folder once, and delete it off my local drive to only have it in the cloud I should probably stop using global policy for that right? Because the next time it syncs it will see the folder gone and delete it from the cloud?

Thank you for your time.

Jon D.

**Comment by jkowalski** [comment]
(I suggest using forum for that - https://kopia.discourse.group, but let me answer it here)

* Currently if you snapshot a directory with compression enabled and later disable the compression it will be a no-op for existing snapshots - the old data will still be compressed but any new data in the directory will not be compressed.

* No, if you remove a snapshot, it only removes record from the snapshot list, but does not immediately delete data from the cloud. Kopia will periodically remove data that is not referenced by ANY snapshot. So if you had file X in two directories, snapshot /A/X and /B/X then delete snapshot from "B", "X" will not be deleted because it's still referenced by /A.

* Kopia will not delete snapshot if it cannot open its root directory, so your data will be safe if you delete the source, but snapshotting will fail (which can break some scripts). Schedules can be specified on a directory basis and inherited from the root, host-level and finally global. To prevent inheritance and set different schedule you should be able to use something like this:

```
$ kopia policy set --global --snapshot-interval 4h
$ kopia policy set /some/directory --snapshot-interval 0 --inherit=false
```

Note that `--inherit=false` prevents ALL policies from being inherited, which may or may not be be what you want,

**Comment by jon-durand** [comment]
Thank you again! And sorry I hadn't realized there was a Discourse forum. I will make sure to use that for all future inquiries.
