### ISSUE TITLE
Configurable disk size limit of the repository?

### ISSUE THREAD

**Issue by dimitarvp** [kopia/kopia#787]
In the scenario of backing up to the free tier of cloud storage services where limits are tight (usually 5GB), would you consider adding a new policy option to allow for setting (and lifting) a total limit of the backup repository?

Then, while creating a new snapshot, and similar to macOS's TimeMachine, keep removing the oldest snapshot until there's enough free space to put the new snapshot in.

**Comment by jkowalski** [comment]
That's an interesting idea, but would be very hard to implement, given how garbage collection is delayed, so it wouldn't be immediately known whether deleting a snapshot will free enough space to be enough.

Also because Kopia stores data in packs, deleting a snapshot may make say 99% of a pack unused and eligible for GC, but because of 1% which is in use, the entire pack (~20MB or so) must be kept alive until next full maintenance which will rewrite it.

**Comment by dimitarvp** [comment]
I see. Then the only option for the user would be to do the following?

- Capture the next backup
- Check total file size of the backup directory
- If over the quota, expire and GC the oldest snapshot
- Rinse and repeat until we're below quota

Would you say that this will work?

**Comment by dimitarvp** [comment]
My previous comment was unclear, sorry for that. What I meant is that I'd aim for a workflow like the above but I am still uncertain if it's at all possible -- f.ex. I cannot find an option to pass to `kopia snapshot list` that makes it return a machine-readable output.

Processing the output of the command with `awk` is relatively trivial but parsing text that's mostly aimed at humans is brittle and scripts can break in future versions of `kopia`, plus you get lines like ` + 1 identical snapshots until 2021-01-19 14:58:40 EET` interspersed with the normal list of snapshots -- which can be fixed with `grep` but again, it's brittle.

So I suppose a different feature request would be:
- Introduce machine-readable outputs of some (or all) commands. JSON is fine. They should also skip helpful messages that are meant for humans in this case (like above: "+N identical snapshots until...").
- `kopia snapshot delete` and `kopia maintenance ...` commands, when outputting in machine-readable format, should include before/after values of the repository size plus how much bytes were deleted/freed. It would really help automation.

Or, you can implement something like `snapshot delete --oldest <path>` if that's going to be easier.

**Comment by jkowalski** [comment]
We should absolutely add  "delete-until-enough-size-below-X" kind of a feature, I was just pointing out that it's currently not safe to do quickly (the protocol to make it safe requires passage of time and multiple rounds of GC). If you know for sure that no snapshots are being taken in the repository by anybody else AND that your storage is strongly consistent (until recently for example Amazon S3 wasn't so) it can be made safe and much faster.

Expiring snapshots one by one will be quite slow since you need to do GC afterwards to really reclaim space.

I would imagine a much more efficient mechanism (but also much more difficult to implement) would be to scan the repository from all roots in parallel and for each object keep track of the maximum time the object was needed and its size.

We can then find the cutoff time and know the exact space savings if we were to drop contents before this date.

Again - this would be unsafe in case of any concurrent access, but would certainly be an interesting feature to add for advanced users w/o concurrency requirements.

**Comment by dimitarvp** [comment]
Exactly. I wouldn't think concurrent access would be the first focus of such a feature. I actually can't imagine two people backing up to the same `kopia` repo at the same time. How would that work? What's the use case?

I am not disputing your good ideas about how to make the process efficient, mind you, but judging by myself, I wouldn't care if a command like `kopia snapshot enforce-quota <repo_dir>` takes 1s, 5s or 30s. I and many others simply script the capturing and uploading of their backups and then call the scripts from inside `crontab`-s.

If I were you I'd write down all my ideas about how to implement a repository quota for the future, but also scratch the immediate itch: namely just make people able to delete the oldest snapshot. I can script a loop where `du -s <repo_dir>` and `kopia snapshot delete --oldest <path>` are ran repeatedly until there is only one snapshot left (so we shouldn't delete further) or the quota has been met.

**Comment by jkowalski** [comment]
N clients backing to shared repository is a common use case where you're able to deduplicate files across hosts (say on a LAN most folks will share the same OS image and some shared documents).

`--oldest` is very easy to implement. I'll be happy to review PR for that.
