### ISSUE TITLE
feature: implement ability to remove objects and their references after snapshot

### ISSUE THREAD

**Issue by jkowalski** [kopia/kopia#799]
There are some scenarios where you may want to get rid of objects (and their references) after they have been snapshotted in the repository:

- you accidentally snapshot a very large file or directory that should have been excluded
- you accidentally snapshot a sensitive file (say containing passwords, etc.)
- repository blobs got damaged and you want to remove references to them from manifests and directory listings.

I propose we add a feature to purge objects, say:

```
$ kopia purge <object-id>
```

This would:

- scan all snapshot roots
- recursively rewrite all directory listings, eliminating entries that had references to the objects to be removed to exclude them
- rewrite snapshots manifests whose object IDs have changed

The contents containing old object will become orphaned and subject to next GC.

Assuming `q` blobs are cached, this actually should be reasonably quick.

More ideas:

```
$ kopia drop-ignored
```

This would re-run old snapshots but apply current ignore rules (similar to migration in-place)

```
$ kopia snapshot verify --fix-unreadable
```

This would automatically rewrite directories to eliminate references to any objects for which the blobs are missing during snapshot verification.

**Comment by xxxliqu1dxxx** [comment]
Great idea! That would have saved me right about now ;) Been working with Jarek on this exact scenario, but ended up deleting the snapshots in questions since I did not have production data; it was not that important to keep. Maintenance was failing, error in snapshot verify, etc. but yes, only 6 files were causing this... and deleting the snapshots basically wiped/un-referenced 815GB of data.. so the maintenance job cleared all of that... including files that technically could have been "good" again.

Luckily this was not prod and/or important data... but I would love for a purge command to avoid this scenario in the future! I look forward to this being implemented.
