### ISSUE TITLE
Password retrieval command

### ISSUE THREAD

**Issue by kamushadenes** [kopia/kopia#807]
I noticed Kopia stores the repository password in `.config/kopia/repository.config.kopia-password` simply obfuscated in base64, which I find quite impacts my trust on the software.

Having the ability to run a command to get this password would allow for way safer implementations while keeping the logic simple.

Since such a command could be anything, like interacting with TPM or an Yubikey, querying from a remote service etc etc, limitless possibilities could be added.

To simplify the implementation, the `repository.config.kopia-password` file could contain a predetermined syntax (like `CMD:blablabla`) that instructs the software to run this command, outputting the file contents as is in case this syntax isn't present.

**Comment by jkowalski** [comment]
All those are great ideas, simply not implemented yet. 

On macOS and Windows password is not stored in a file but in OS-specific keychain tied to user login password (you can store it in a file if you wish). 

On Linux you can also do that, but since this mechanism is not reliable (it's tied to Gnome keyring), it is disabled by default, the relevant option is `--use-keyring` when connecting to repository.

BTW. The user's home directory (whether encrypted or not) is usually considered secure (it typically already contains lots of other sensitive data, such as browser cookies, various authentication tokens, .boto, .netrc, etc.) so hiding the password from the user seems counter-productive.

**Comment by kamushadenes** [comment]
@jkowalski added primitive support on this draft PR https://github.com/kopia/kopia/pull/808

**Comment by jtssi** [comment]
> All those are great ideas, simply not implemented yet.
> 
> On macOS and Windows password is not stored in a file but in OS-specific keychain tied to user login password (you can store it in a file if you wish).


Hi, sorry to bring this up again, but how do I save the repository password in a Windows file?
