### ISSUE TITLE
[FR]Google Drive support

### ISSUE THREAD

**Issue by yurikoles** [kopia/kopia#90]
Hi @jkowalski,

Could you please implement native Google Drive support, because `gcsf` seems unreliable?

**Comment by yurikoles** [comment]
Because Google Drive prices seems more attractive than Google Cloud Storage.

**Comment by eras** [comment]
Does the rclone support introduced by #545 satisfy this request?

**Comment by zyradyl** [comment]
@yurikoles i'm going to close this under the assumption #545 resolves it. feel free to open a new issue if you're running into problems with the rclone backend! 😄

**Comment by julio-lopez** [comment]
Contributions are welcome.

Quoting Jarek's comment from the #kopia Slack channel:

> it absolutely could be done, we can probably talk about bringing in {Google,One}Drive as first-class providers. Building a provider requires implementing about 5 non-trivial methods (GetBlob, GetMetadata, PutBlob, DeleteBlob, ListBlobs) and some trivial ones.
A full-fledged provider is only about 300-500 lines of code and there’s reasonably extensive test suite to validate basic properties of each provider that are required by Kopia + maybe 100 lines of code for the UI and special CLI flags, so definitely a good starter project that requires little knowledge of how the rest of kopia works.

**Comment by xkxx** [comment]
I can try to work on this. I want to know if anyone else is working on this feature concurrently?

**Comment by jkowalski** [comment]
nobody is working on it, AFAIK, go ahead!

**Comment by xkxx** [comment]
# Implementation Plan

Code directory: `kopia/repo/blob/gdrive`
Package: `gdrive`

The implementation will be loosely based on the GCS backend, but with GDrive APIs. We will integrate with the official go client for GDrive `google.golang.org/api/drive/v3`. 

## Background

Google Drive itself needs no introduction. Some challenges arise from the Drive architecture and the permission model. These are:

**Permissions**: Google no longer gives out blanket Drive access to all developers. To do this, they would have to go through a security review. Since we expect each user to create their own developer account to use with Kopia, this is not realistic. Instead, [Google recommends](https://developers.google.com/drive/api/v3/about-auth) `drive.file` or `drive.appdata` permission scopes, which give access to specific files or a hidden per-application directory, respectively. I'll experiment with `drive.file` scope first and see if it meets Kopia's needs.

**ID mapping**: Drive API allows get/update/delete an individual file by a fileId or listing files by file display names. In other words, there's no direct way to read a file by the file display name. If the drive client can generate the blobId instead of receiving it from the caller, we can make blobId == fileId, but that's much larger of an infra change. Therefore, accessing a file will be 2 roundtrips: look up the fileId for a blob, and access the file by fileId. We can try to optimize access latency by introducing an fileId cache, explained below, and I certainly appreciate other suggestions.

## Design

The user will provide a Drive folder that Kopia will own and manage. We will use this directory to store a flat list of blobs. I'm hopeful that the user providing Kopia access to the folder means that Kopia can freely create files within it, which we'll find out soon enough. 

**CRUD**: When Kopia stores a new blob, a file will be created with the file name `blobId.kopia` and mimeType `application/x-kopia`. Reading, deleting and replacing a blob thus correspond to the respective action on the drive file.

**Authentication**: The authentication logic is reused from GCS: with Google OAuth tokens. Kopia will use the `drive.file` scope, as explained above.

**ID caching**: The gdrive client struct will contain an ID cache, which is a map of blobId -> Drive fileId. This cache is populated by ListBlob initially, and in subsequent per-blob operations. When a blob access call is received, a cached look up is performed first. In case of a cache miss, we perform a query against drive and store the result in the cache. Since neither blobId nor fileId are mutable, the mapping is stable and no cache invalidation is required.

## Testing

This is where I'm least sure about and would appreciate more feedback. While unit tests are easy, testing against a real Drive account in a continuous test environment is likely going to trigger Google-side throttling and usage limiting. Do you have any experience for this scenario?

**Comment by xkxx** [comment]
@jkowalski : Some questions for you.

I have worked at this a bit and got a blob implementation that passes the validation tests. I discovered an issue with the consistency model of Drive though, and I want to double check with you on my solution before I send it in for a review.

Recall that there's no direct way to retrieve a file by its file display name. Instead, one needs to perform a lookup `drive.list` with the file name to get a FileId follow by a retrieval `drive.get` using said id.

What I've found is that `drive.list` is not read-after-write consistent when it comes to file names, for both partial and exact matches. Other aspect of the query is ok, for example, look up by parent folders or mime types. This is possibly due to Drive using a full-text index for file display name search and `drive.create` returning before the index is fully updated. `drive.get` seems to be strongly consistent, and this is backed up by [third-party research](https://blog.cloudrail.com/compare-consistency-models-of-cloud-storage-services/). What this means is that in a naive Google Drive driver:

- GetBlob / GetBlobMetadata: Without a client-side cache, these calls may return `NotFound` for a newly created blob. This happens x% of the time and is reproducible.
- ListBlob: Listing blobs by a prefix can be inconsistent, for the same reason.

There are a couple of approaches that can solve this:

1) Block writes. PutBlob won't return until the full-text index is complete. We don't know when it's gonna be complete, but we can sniff by trying `drive.list` search for the created blob until it shows up. This will definitely increase write latencies. Or
2) Don't use file name search. Always list the entire directory with `drive.list` and then use a local filter, bypassing the full-text index. This won't be pretty on folders with millions of blobs, but is that something that actually happens? Also this predicament is no worse than on a physical file system. GetBlob / GetBlobMetadata may see a worse-case O(n) now, but it's largely mitigated by the FileId cache mentioned in the above design, especially for one-seat usage.

My WIP implementation in https://github.com/xkxx/kopia uses 2) approach, but I would love to hear your thoughts. I will update my design proposal when I hear back from you.

Also fun fact, `drive.list` will always fail if one tries a file name prefix match with more than 26 characters. So I've resorted to truncating the prefix. Quite excite!

Best,

xkxx

**Comment by jkowalski** [comment]
You have some made some Interesting discoveries. I was suspecting consistency to be a problem, similar to what folks have seen with OneDrive.

I have few answers/suggestions/observations/hints that may help here:

1. Kopia content manager can generally tolerate PutBlob->ListBlobs and DeleteBlob->ListBlobs being eventually consistent (up to 20-30 minutes should generally just work, Kopia maintains higher-level own-writes cache) but expects GetBlob/GetMetadata after PutBlob to be strongly consistent.

2. Given that GetBlob()/GetMetadata() are typically called with blob IDs we expect to exist (perhaps not in the validation suite, but that's how Kopia works), I'm wondering if the file name search + aggressive retrying when not found is a viable implementation strategy for GetBlob/GetMetadata. It should be really rare to call GetBlob() when it does not really exist.

3. (This may be completely wrong direction...), but I'm wondering if we could keep the blob ID->file ID cache in some file(s) in the drive itself - either mutable or immutable/merged on reads? I'm not sure if this would really perform any better than the index server-side, but theoretically we can achieve better caching. That's a lot of work, though, but because it's strictly a cache (and we can always fall back to list by name) it may work quite well. Each client can download cached blob->file maps on startup or periodically and persist them on local disk for super quick access. Writers would write to both GDrive and local disk.

4. As for testing, I can set up CI/CD workflow that runs a small test every few hours. We already have that for other providers. Google Drive is actually tested via rclone and seem to be reasonably stable, although it runs very basic operations only and not the extensive validation.

5. As for how many files we can expect, folks on S3/GCS have repositories upwards of 50TB, so that can go up to millions of blobs. Given that GDrives tend to be more limited in size, I think handling 100K files would be sufficient, as long as listing that is 1-2 minutes we should be fine in terms of usability. From performance perspective it's only critical to be able to list blobs starting with "x", the others are only listed during maintenance.

6. The document listing consistency models is quite outdated, S3 and GCS are strongly consistent these days. 

7. Blocking write until list returns the item does not really guarantee that next list call will also succeed, it's an approximation, but not a hard guarantee.

I hope my answers are at least a bit useful, and thanks again for tackling the problem. GDrive is much more challenging than others, since we have to emulate so much of the semantics.

**Comment by xkxx** [comment]
Thanks for the detailed response! I have some more questions and thoughts to run by you:

**Questions:**

Re: 5 - Can you talk more about how blobID prefixes are used? Are they for blob types, different node UUIDs, or others? Is there any prefix >26 chars in practice? If there is a small set of stable prefixes, we can exploit that by turning these prefixes into folders which in Drive don't seem to suffer from consistency issues. It won't be a general purpose blob store anymore, and relying on usage patterns might be a little brittle.

**On ListBlobs:**
> 1. Kopia content manager can generally tolerate PutBlob->ListBlobs and DeleteBlob->ListBlobs being eventually consistent

That's actually great to know that ListBlobs can be lenient consistency-wise. We should still be able to use `drive.list` with prefix search then. 20 minutes should be plenty for Drive save for an actual outage.

**On GetBlob / GetMetadata:**
> 2. Given that GetBlob()/GetMetadata() are typically called with blob IDs we expect to exist 

Thanks for this information as well! Considering this, I'm leaning towards this:
- First an in-mem FileId cache. This addresses 100% of the same-node read-after-write cases.
- Then file name search + aggressive retrying. This addresses cross-node interactions or in case a node's cache is lost due to a restart

**Other responses:**

Re: 3 - I thought about this one as well! I think that would work for single-access scenarios. If the Drive folder is shared, though, we don't have a mutex / append-only write mechanism in Drive. This problem would really be much simpler if we can enforce one-Drive-folder-per-node, t's easy to create Drive folders and thus there's no reason to share them.

Re: 4 - Great, we can use the same test setup as rclone in that case. I have been hammering my personal account all day without ill effects, I'm only concerned with potential flakiness and drawing the ire of some SRE in the long term.

Best,

xkxx
