### ISSUE TITLE
[Feature] Provide a default list of "Never Compress" extensions. Clarify syntax.

### ISSUE THREAD

**Issue by ZoomRmc** [kopia/kopia#906]
Global policy should probably include a set of default extensions to populate "Never Compress" list. At least until #812 is implemented. Compressing high-entropy files severely impacts compression speed with many algorithms, so skipping unnecessary work can increase the speed significantly.

Also, there's currently no clarification on the syntax of this list. Are `*` or `*.` necessary before extensions? Are comments supported? Empty lines?

I attach a sample list of non-compressible files (in an arbitrary format) which can be used as a starting point. Extensions are grouped by type, most are supplied with an explanatory comment.
[nevercompress.txt](https://github.com/kopia/kopia/files/6183520/nevercompress.txt)

**Comment by bbccdd** [comment]
Thanks @ZoomRmc great list. Do you have clarification on the syntax already? Should we use '*' or '*'? And, assuming filters being case sensitive we should also include the capitalized variants (e.g. .MP4 alongside .mp4 or use .[Mm][Pp]4 which is less readable.

Is it still the most recent list? I'll run through it myself to see if I can improve it.

**Comment by bbccdd** [comment]
1. The GUI's could show one or two examples to clarify syntax like so (indeed before something like #812 is implemented):
![image](https://user-images.githubusercontent.com/29344993/115550726-7bcb6780-a2aa-11eb-99c6-22c915797b5e.png)

2. I've edited your list to a plain text list you can copy'n paste into the 'never compress'-section of the GUI's. 
b) JSON format you can copy'n paste into either the global policy (using "kopia policy edit --global") and  

PS I've used a non-global policy to copy'n paste the list of extension and used the CLI to extract the JSON-format from the policy.

a) you can copy'n paste this list for your **never compres** list 
.7[Zz]
.alz
.ALZ
.bz
.BZ
.bz2
.BZ2
.cab
.CAB
.cbr
.CBR
.cbz
.CBZ
.deb
.DEB
.dl_
.DL_
.dsft
.DSFT
.ex_
.EX_
.gz
.GZ
.jar
.JAR
.lmza
.LMZA
.lzo
.LZO
.mpkg
.MPKG
.msi
.MSI
.msp
.MSP
.msu
.MSU
.pet
.PET
.rar
.RAR
.sft
.SFT
.sit
.SIT
.sitx
.SITX
.sy_
.SY_
.tgz
.TGZ
.tbz2
.TBZ2
.txz
.TXZ
.war
.WAR
.wim
.WIM
.xar
.XAR
.xz
.XZ
.zip
.ZIP
.zipx
.ZIPx
.zst
.ZST
.3gp
.3GP
.aa3
.AA3
.aac
.AAC
.aif
.AIF
.ape
.APE
.flac
.FLAC
.gsm
.QSM
.iff
.IFF
.m4a
.M4A
.mp3
.MP3
.mpa
.MPA
.mpc
.MPC
.ra
.RA
.ofr
.OFR
.ofs
.OFS
.ogg
.OGG
.opus
.OPUS
.wma
.WMA
.wv
.3g2
.3G2
.3gp
.3GP
.asf
.ASF
.asx
.ASX
.avi
.AVI
.bsf
.BSF
.divx
.DIVX
.f4v
.F4V
.flv
.FLV
.hdmov
.HDMOV
.m2p
.M3P
.m4v
.M4V
.mkv
.MKV
.mov
.MOV
.mp4
.MP4
.mpg
.MPQ
.mpeg
.MPEG
.mts
.MTS
.ogm
.OGM
.ogv
.OGV
.rm
.RM
.swf
.SWF
.trp
.TRP
.ts
.TS
.vob
.VOB
.webm
.WEBM
.wmv
.WMV
.wtv
.WTV
.emz
.EMZ
.gif
.GIF
.j2c
.J2C
.jpeg
.JPEG
.jpg
.JPG
.nef
.NEF
.pamp
.PAMP
.pdn
.PDN
.png
.PNG
.pspimage
.PSPIMAGE
.tif
.TIF
.tiff
.TIFF
.DNG
.CR2
.dmg
.DMG
.tib
.TIB
.DMG
.deb
.DEB
.aes
.AES
.axx
.AXX
.gpg
.GPG
.hc
.HC
.kdbx
.KDBX
.tc
.TC
.tpm
.TPM
.fve
.FVE
.apk
.APK
.eftx
.EFTX
.sdg
.SDG
.thmx
.THMX
.vsix
.VSIX
.vsv
.VSV
.wmz
.WMZ
.xpi
.XPI
.eot
.EOT
.woff
.WOFF
.bik
.BIK
.mpq
.MPQ
.docx
.DOCX
.docm
.DOCM
.dotm
.DOTM
.dotx
.DOTX
.epub
.EPUB
.graffle
.GRAFFLE
.hxs
.HXS
.max
.MAX
.mobi
.MOBI
.mshc
.MSHC
.odp
.ODP
.ods
.ODS
.odt
.ODT
.otp
.OTP
.ots
.OTS
.ott
.OTT
.pages
.PAGES
.pptx
.PPTX
.stw
.STW
.trf
.TRF
.webarchive
.WEBARCHIVE
.xlsx
.XLSX
.xlsm
.XLSM
.xlsb
.XLSB
.xps
.XPS
.d
.D
.dess
.dess
.i
.I
.idx
.IDX
.nupkg
.NUPKG
.pack
.PACK
.swz
.SWZ
.bz2
.BZ2
.gz
.GZ
.tgz
.TGZ
.lz
.LZ
.lmza
.LMZA
.lz4
.LZ4
.z
.Z
.7z
.7Z
.xz
.XZ
.s7z
.S7Z
.ace
.ACE
.arj
.ARJ
.rar
.RAR
.cab
.CAB
.dmg
.DMG
.zip
.ZIP
.deb
.DEB
.rpm
.RPM
.avi
.AVI
.mpg
.MPG
.mp4
.MP4
.mp3
.MP3
.wmv
.WMV
.flv
.FLV
.jpg
.JPG
.jpeg
.JPEG
.m4v
.M4v
.mpg
.MPG
.vob
.VOB
.mov
.MOV
.mkv
.MKV

**Comment by jkowalski** [comment]
I think it would be better to have this list baked into Kopia directly and have a simple flag that enables it (`--skip-internally-compressed-files` or something).

Adding a boolean flag to `compression_policy.go` plus a new`kopia policy set` flag to control it and one additional check inside `CompressorForFile` should be all that's needed.  I'll be happy to merge a PR that implements it.

**Comment by ZoomRmc** [comment]
Please, don't bake it in in a non-editable way. There will definitely be users who need *almost* the entire list but not quite.

And could you address the clarification of the syntax bit?

**Comment by jkowalski** [comment]
Can you give me an example when you want almost the entire list (that is have a file with an extension that's normally non-compressible that sometimes is?). I can think of `.zip` which supports uncompressed option - we for those cases we should probably not include them in the default list anyway.

**Comment by jkowalski** [comment]
BTW, instead of one, could also have multiple curated lists like that (probably no more than 3, to not overwhelm people with choice that rarely matters). 

Alternatively have one list, but have each item in list could have confidence score (JPEG=100%, ZIP=90%, etc.) and people would select the threshold.

**Comment by ZoomRmc** [comment]
Why not just explicitly populate (or have a button doing so) the list in the general policy and be done with it? Probably a nice idea to have the list as a separate file in the source code too.

Uncompressed archives is just what I have in mind, but excluding zip files from a default list defeats the purpose.

**Comment by jkowalski** [comment]
One more thing comes to mind. We could have two lists: 

- "never compress" (includes JPEG)
- "auto compression" (includes ZIP, ISO, etc.)

For the auto compression we can take advantage of the fact that kopia splits each file into chunks of 4-16 MB and compresses them individually. The compressibility of the first chunk could determine whether we attempt to compress the rest or simply store it uncompressed - this is not perfect, though, if you have an uncompressed ZIP with compressed JPEGs in it + other uncompressed files.

**Comment by bbccdd** [comment]
OK, combining a few things.

Compression could be turned on by default and simple to disable. The 'compression' tab in the GUIs could be hidden by default and visible when 'advanced mode' is selected. Always and never compress remain available for power users. An 'auto compress' option would be the default.

Idea's for reaching this state:

- Allow 'advanced' users to select always- and never compress.
- Limit the compression algorthms choices available. 
  - Now, there are [3](https://kopia.io/docs/features/#compression), but they have various sub-options causing confusion in terms of compression vs storage vs compute performance vs **futureproffness**. **Perhaps just choose one,** say s2-default (as the default). 
  - Document why x (the chosen default) is the default and how to other options are for very specific use cases to build trust in that your data can be reliably decompressed also in a decade or so.
- "auto compression" is the default "not overwhelm people with choice that rarely matters".
  - Run a 'kopia **benchmark compression**' and **automatically choose** options (algorithm and its configuration) favouring throughput first, compression level second. Advanced users may change this similar to how crypto and splitting algo's can be changed.
    - Look into more **aggressively** applying the S2 posibility of the "Ability to quickly **skip forward in compressed stream**" https://github.com/klauspost/compress/tree/master/s2
  - Untill a better option has been found, use a list of the most common file extensions not suitable for compression to populate 'never compress' and 'always compress'. Again, adjustable if desired.
  - During a snapshot (or estimate of a snapshot) compression could perhaps (I'm unformiliar with the technology stack) benchmark compression by compressing the first bytes of a file and skip compression on all data of that file if the compression level is below 5%. Or **always compress the first bytes and based on compression cost/benefit skip the rest of the file** or continue compression for the file.
- In the documentation explain how all possible options are future proof and great tradeoffs between throughput/compute load and storage capacity needed. **I would happily write and/or review such paragraphs**.

All-in all I think the 'compression' feature can fully automatically be applied (out of sight for most users) with fair tradeofs for most and plenty of manouverability for those with vastly different use cases.

**Comment by ZoomRmc** [comment]
First of all, let's discuss auto-compression in #812. I agree it should be the default and can probably replace the list-based compression altogether.

Regarding issues outlined here, let's first address the most actionable: If @jkowalski would be so kind to clarify the syntax of the never/always-compress lists I'm sure we'll promptly populate the corresponding documentation.

Speaking of never-compressed list, if we would populate it with the default values, this opens the possibility to enable compression by default which will work properly for 95% of users.

**Comment by bbccdd** [comment]
The syntax is simply the extension with globbing support.

e.g.
'.7[Zz]' would expand to '.7z' and '.7Z'
Or for readability (and searchability) simply write:
.7z
.7Z

No need to specify a '*'. Test it for yourself with a large file (VM/ISO/movie) to see it in action.

A simple idea to clarify the syntax would be to pre-fill one or two common excludes (e.g. .mp4 & .avi) like in [the mockup above](https://github.com/kopia/kopia/issues/906#issuecomment-824078683).

**Comment by jkowalski** [comment]
I've been thinking about this a bit more:

Recompression of already-compressed file is pointless in virtually all cases, even if the original compression is not great. To get any meaningful savings you'd need to decompress and re-compress.

The only other reason to want to compress something that's on the well-known list of files that are "never compressible" would to be if you had a counter-example - for example a ZIP file that is not compressed.

Here's what I think is going to solve the 99% case:

* we will have a baked-in list of extensions that are non-compressible - we can start with a list from this issue and evolve it
* we will add policy option `Attempt to compress non-compressible file extensions` with default = false
* to opt out for a small number of extensions, we already have `Never compress extensions` options
* to always attempt compression - the user can set `Attempt to compress non-compressible file extensions=true` which i think will be rare.

Thoughts?

**Comment by ZoomRmc** [comment]
My main argument is that we're compressing chunks, and how compressible the file is can be not uniform.
The auto-compression looks like the way, especially considering lz4 is almost free computationally. If it's implemented, manual exclusion and tuning has to become the non-default option.
Some examples of possibly compressible files from the list above is mentioned in #812

Also, why bake the list in? I suggest pre-populating the global policy if the compression is enabled.

**Comment by jkowalski** [comment]
Ok, I did some testing and am convinced now we should do #812 instead of this, although `s2-default` is much faster than `lz4` in all my tests.

I measured throughput of compressing 2 files - both around 8 MB and compression using s2-default is blazing fast (compressible file was a text log, non-compressible was a zip):

* Core i5-8260U - Windows - 1.9 GB/s (compressible), 2.9 GB/s (non-compressible)
* Core i5-7600K - Windows - 2.9 GB/s (compressible), 3.2 GB/s (non-compressible)
* AMD Ryzen 9 3950X - Linux - 3.9 GiB/s (compressible), 5.4 GB/s (non-compressible)
* Apple M1 Pro (2021 MacBook Pro) - 3.6 GiB/s (compressible), 11.8 GB/s (non-compressible)
* Apple M1 (2020 Mac Mini) - 3.1 GiB/s (compressible), 12 GB/s (non-compressible)
* Raspberry PI 4 using 64-bit OS - Linux - 277.3 MiB/s (compressible), 600 MB/s (non-compressible)
* Raspberry PI 4 using 32-bit OS - Linux - 171 MB/s (compressible), 278 MB/s (non-compressible)

**Comment by luboslives** [comment]
Since this and the related issue appear to not have been implemented yet, I've updated the suggested list of extensions for us in 2026. First is the full case-sensitive list without any globbing. Following it is a heavily compacted one that uses globbing. Use as needed:

.3G2
.3GP
.3g2
.3gp
.7Z
.7z
.AA3
.AAC
.ACE
.AES
.AIF
.ALZ
.APE
.APK
.APNG
.ARJ
.ASF
.ASX
.AV1
.AVI
.AVIF
.AXX
.BIK
.BR
.BSF
.BZ
.BZ2
.BZ3
.CAB
.CBR
.CBZ
.CPIO
.CR2
.DEB
.DESS
.DIVX
.DL_
.DMG
.DNG
.DOCM
.DOCX
.DOTM
.DOTX
.DSFT
.EFTX
.EMZ
.EOT
.EPUB
.EX_
.F4V
.FLAC
.FLV
.FVE
.GIF
.GPG
.GRAFFLE
.GSM
.GZ
.HC
.HDMOV
.HEIC
.HEIF
.HXS
.IDX
.IFF
.J2C
.JAR
.JPEG
.JPG
.JXL
.JXR
.KDBX
.LMZA
.LZ
.LZ4
.LZH
.LZMA
.LZO
.M2P
.M3P
.M4A
.M4V
.M4v
.MAX
.MKV
.MOBI
.MOV
.MP3
.MP4
.MPA
.MPC
.MPEG
.MPG
.MPKG
.MPQ
.MSHC
.MSI
.MSP
.MSU
.MTS
.NEF
.NUPKG
.ODP
.ODS
.ODT
.OFR
.OFS
.OGG
.OGM
.OGV
.OPUS
.OTP
.OTS
.OTT
.PACK
.PAGES
.PAMP
.PDN
.PET
.PNG
.PPTX
.PSPIMAGE
.QSM
.RA
.RAR
.RM
.RPM
.S7Z
.SDG
.SFT
.SIT
.SITX
.STW
.SWF
.SWZ
.SY_
.TAR
.TAR.BR
.TAR.BZ2
.TAR.GZ
.TAR.LZ
.TAR.LZMA
.TAR.XZ
.TAR.Z
.TAR.ZST
.TAZ
.TBR
.TBZ
.TBZ2
.TC
.TGZ
.THMX
.TIB
.TIF
.TIFF
.TLZ
.TLZ4
.TLZMA
.TPM
.TRF
.TRP
.TS
.TXZ
.TZO
.TZST
.VOB
.VSIX
.VSV
.WAR
.WEBARCHIVE
.WEBM
.WEBP
.WIM
.WMA
.WMV
.WMZ
.WOFF
.WOFF2
.WTV
.WV
.XAR
.XLSB
.XLSM
.XLSX
.XPI
.XPS
.XZ
.ZIP
.ZIPX
.ZIPx
.ZPAQ
.ZST
.ZSTD
.aa3
.aac
.ace
.aes
.aif
.alz
.ape
.apk
.apng
.arj
.asf
.asx
.av1
.avi
.avif
.axx
.bik
.br
.bsf
.bz
.bz2
.bz3
.cab
.cbr
.cbz
.cpio
.cr2
.deb
.dess
.divx
.dl_
.dmg
.dng
.docm
.docx
.dotm
.dotx
.dsft
.eftx
.emz
.eot
.epub
.ex_
.f4v
.flac
.flv
.fve
.gif
.gpg
.graffle
.gsm
.gz
.hc
.hdmov
.heic
.heif
.hxs
.idx
.iff
.j2c
.jar
.jpeg
.jpg
.jxl
.jxr
.kdbx
.lmza
.lz
.lz4
.lzh
.lzma
.lzo
.m2p
.m3p
.m4a
.m4v
.max
.mkv
.mobi
.mov
.mp3
.mp4
.mpa
.mpc
.mpeg
.mpg
.mpkg
.mpq
.mshc
.msi
.msp
.msu
.mts
.nef
.nupkg
.odp
.ods
.odt
.ofr
.ofs
.ogg
.ogm
.ogv
.opus
.otp
.ots
.ott
.pack
.pages
.pamp
.pdn
.pet
.png
.pptx
.pspimage
.qsm
.ra
.rar
.rm
.rpm
.s7z
.sdg
.sft
.sit
.sitx
.stw
.swf
.swz
.sy_
.tar
.tar.br
.tar.bz2
.tar.gz
.tar.lz
.tar.lzma
.tar.xz
.tar.z
.tar.zst
.taz
.tbr
.tbz
.tbz2
.tc
.tgz
.thmx
.tib
.tif
.tiff
.tlz
.tlz4
.tlzma
.tpm
.trf
.trp
.ts
.txz
.tzo
.tzst
.vob
.vsix
.vsv
.war
.webarchive
.webm
.webp
.wim
.wma
.wmv
.wmz
.woff
.woff2
.wtv
.wv
.xar
.xlsb
.xlsm
.xlsx
.xpi
.xps
.xz
.zip
.zipx
.zpaq
.zst
.zstd

Compacted list provided by Kilo Code and GLM 5.2:

```
.3[Gg][2Pp]
.7[Zz]
.[Aa][Aa][3Cc]
.[Aa][Cc][Ee]
.[Aa][Ee][Ss]
.[Aa][Ii][Ff]
.[Aa][Ll][Zz]
.[Aa][Pp][EKek]
.[Aa][Pp][Nn][Gg]
.[Aa][Rr][Jj]
.[Aa][Ss][FXfx]
.[Aa][Vv][1Ii]
.[Aa][Vv][Ii][Ff]
.[Aa][Xx][Xx]
.[Bb][Ii][Kk]
.[Bb][RZrz]
.[Bb][Ss][Ff]
.[Bb][Zz][23]
.[Cc][Aa][Bb]
.[Cc][Bb][RZrz]
.[Cc][Pp][Ii][Oo]
.[Cc][Rr][2]
.[Dd][Ee][Bb]
.[Dd][Ee][Ss][Ss]
.[Dd][Ii][Vv][Xx]
.[Dd][Ll][_]
.[Dd][Mm][Gg]
.[Dd][Nn][Gg]
.[Dd][Oo][Cc][MXmx]
.[Dd][Oo][Tt][MXmx]
.[Dd][Ss][Ff][Tt]
.[Ee][Ff][Tt][Xx]
.[Ee][Mm][Zz]
.[Ee][Oo][Tt]
.[Ee][Pp][Uu][Bb]
.[Ee][Xx][_]
.[Ff]4[Vv]
.[Ff][Ll][Aa][Cc]
.[Ff][Ll][Vv]
.[Ff][Vv][Ee]
.[Gg][Ii][Ff]
.[Gg][Pp][Gg]
.[Gg][Rr][Aa][Ff][Ff][Ll][Ee]
.[Gg][Ss][Mm]
.[Gg][Zz]
.[Hh][Cc]
.[Hh][Dd][Mm][Oo][Vv]
.[Hh][Ee][Ii][CFcf]
.[Hh][Xx][Ss]
.[Ii][Dd][Xx]
.[Ii][Ff][Ff]
.[Jj]2[Cc]
.[Jj][Aa][Rr]
.[Jj][Pp][Ee][Gg]
.[Jj][Pp][Gg]
.[Jj][Xx][LRlr]
.[Kk][Dd][Bb][Xx]
.[Ll][Mm][Zz][Aa]
.[Ll][Zz]
.[Ll][Zz][4HOho]
.[Ll][Zz][Mm][Aa]
.[Mm]2[Pp]
.[Mm]3[Pp]
.[Mm]4[AVav]
.[Mm][Aa][Xx]
.[Mm][Kk][Vv]
.[Mm][Oo][Bb][Ii]
.[Mm][Oo][Vv]
.[Mm][Pp][34ACGQacgq]
.[Mm][Pp][Ee][Gg]
.[Mm][Pp][Kk][Gg]
.[Mm][Ss][Hh][Cc]
.[Mm][Ss][IPUipu]
.[Mm][Tt][Ss]
.[Nn][Ee][Ff]
.[Nn][Uu][Pp][Kk][Gg]
.[Oo][Dd][PSTpst]
.[Oo][Ff][RSrs]
.[Oo][Gg][GMVgmv]
.[Oo][Pp][Uu][Ss]
.[Oo][Tt][PSTpst]
.[Pp][Aa][Cc][Kk]
.[Pp][Aa][Gg][Ee][Ss]
.[Pp][Aa][Mm][Pp]
.[Pp][Dd][Nn]
.[Pp][Ee][Tt]
.[Pp][Nn][Gg]
.[Pp][Pp][Tt][Xx]
.[Pp][Ss][Pp][Ii][Mm][Aa][Gg][Ee]
.[Qq][Ss][Mm]
.[Rr][AMam]
.[Rr][Aa][Rr]
.[Rr][Pp][Mm]
.[Ss]7[Zz]
.[Ss][Dd][Gg]
.[Ss][Ff][Tt]
.[Ss][Ii][Tt]
.[Ss][Ii][Tt][Xx]
.[Ss][Tt][Ww]
.[Ss][Ww][FZfz]
.[Ss][Yy][_]
.[Tt][Aa][RZrz]
.[Tt][Aa][Rr].[Bb][Rr]
.[Tt][Aa][Rr].[Bb][Zz][2]
.[Tt][Aa][Rr].[Gg][Zz]
.[Tt][Aa][Rr].[Ll][Zz]
.[Tt][Aa][Rr].[Ll][Zz][Mm][Aa]
.[Tt][Aa][Rr].[Xx][Zz]
.[Tt][Aa][Rr].[Zz]
.[Tt][Aa][Rr].[Zz][Ss][Tt]
.[Tt][Bb][RZrz]
.[Tt][Bb][Zz][2]
.[Tt][CScs]
.[Tt][Gg][Zz]
.[Tt][Hh][Mm][Xx]
.[Tt][Ii][BFbf]
.[Tt][Ii][Ff][Ff]
.[Tt][Ll][Zz]
.[Tt][Ll][Zz][4]
.[Tt][Ll][Zz][Mm][Aa]
.[Tt][Pp][Mm]
.[Tt][Rr][FPfp]
.[Tt][Xx][Zz]
.[Tt][Zz][Oo]
.[Tt][Zz][Ss][Tt]
.[Vv][Oo][Bb]
.[Vv][Ss][Ii][Xx]
.[Vv][Ss][Vv]
.[Ww][Aa][Rr]
.[Ww][Ee][Bb][Aa][Rr][Cc][Hh][Ii][Vv][Ee]
.[Ww][Ee][Bb][MPmp]
.[Ww][Ii][Mm]
.[Ww][Mm][AVZavz]
.[Ww][Oo][Ff][Ff]
.[Ww][Oo][Ff][Ff][2]
.[Ww][Tt][Vv]
.[Ww][Vv]
.[Xx][Aa][Rr]
.[Xx][Ll][Ss][BMXbmx]
.[Xx][Pp][ISis]
.[Xx][Zz]
.[Zz][Ii][Pp]
.[Zz][Ii][Pp][Xx]
.[Zz][Pp][Aa][Qq]
.[Zz][Ss][Tt]
.[Zz][Ss][Tt][Dd]
```
