### ISSUE TITLE
Password storage problem with OSX and remote shells.

### ISSUE THREAD

**Issue by oderwat** [kopia/kopia#939]
It seems like a stored password is not found when I connect to the system through ssh/mosh. This makes all of my scripts quite useless and would need to add the password to the filesystem or have it in the command. Is there a way to get around this limitation?

**Comment by jkowalski** [comment]
When connecting to macOS over ssh, you need to unlock default keychain using `security unlock-keychain -p <password>`

Alternatively pass kopia password using `KOPIA_PASSWORD` environment variable.

**Comment by oderwat** [comment]
Thank you for the reply. Is there a way to avoid getting a key-chain password on `kopia create`? I only see `--use-keychain`, which seems to be always on for OSX anyways?

**Comment by jkowalski** [comment]
To disable it, pass `--no-use-keychain` - that's the case for all boolean flags.

**Comment by oderwat** [comment]
OK. Would be nice if that would be explained somehow. Or did I miss something obvious?

**Comment by jkowalski** [comment]
Each of the auto-generated pages like this https://kopia.io/docs/reference/command-line/common/repository-create-filesystem/ shows all supported flags, but  `--[no-]use-keychain` is actually not there, the problem here is that the doc generator (`site/cli2md`) runs on Linux so does not even see this macOS-specific flag at all. This is probably fixable with some effort. Also we might add some general-purpose comment about flag syntax.

PRs are welcome

**Comment by oderwat** [comment]
I see. I like Kopia a lot and think you are doing a great job! I hope I find a way to contribute in the future.
