### ISSUE TITLE
Global policies ignored

### ISSUE THREAD

**Issue by darkdragon-001** [kopia/kopia#990]
When I add `.git/` to my local policy, it excludes all `.git` folders anywhere in the tree. If I add the same rule to my global policy (`*`, `*`, `*`), then it is included in the backup.

Kopia 0.8.2

**Comment by jkowalski** [comment]
What does `kopia policy ls` return?

**Comment by xbb** [comment]
I also have some issues inheriting ignore rules with kopia 0.8.4 for windows

I have some global ignore patterns configured and schedules

I added a new policy for a directory and some ignore patterns.
In this case the global ignore patterns are not applied (ignore parent rules unchecked), meaning the rules are not merged with the global policy, is this by design?

Furthermore, selecting disable parent policy evaluation seems to break the policy, no ignore rules are applied except the default (builtin ones?)  and while the policy is listed with `kopia policy list` it won't show its rules with `kopia policy show ... --json` but only:

```
{"retention":{},"files":{},"errorHandling":{},"scheduling":{},"compression":{},"actions":{}}
```

`--log-level=debug` doesn't show any errors

**Comment by mjpieters** [comment]
I ran into this as well. Basically, if you set ignore patterns in a snapshot policy, **the global ignores are not use**. There is no merging of patterns.

This all _should_ happen in `fs/ignorefs/ignorefs.go`, but doesn't, because the parent context ignore patterns are never processed.

- [`buildContext()`](https://github.com/kopia/kopia/blob/e0e7f66a90e6c25120fb3dcd4db1df223041147e/fs/ignorefs/ignorefs.go#L170-L210) takes the parent context and creates a new [`ignoreContext` struct](https://github.com/kopia/kopia/blob/e0e7f66a90e6c25120fb3dcd4db1df223041147e/fs/ignorefs/ignorefs.go#L23-L33). The `matchers` slice in this object is left empty.
- it then calls [`overrideFromPolicy()`](https://github.com/kopia/kopia/blob/e0e7f66a90e6c25120fb3dcd4db1df223041147e/fs/ignorefs/ignorefs.go#L212-L239) to update the `ignoreContext` object with the rules from the current policy. This will set the `matcher` slice to `nil` if `NoParentIgnoreRules` is set (clearing the slice), then uses `append()` to add new  `matcher` with the ignore rules from the current policy (using `wcmatch.NewWildcardMatcher()` to create the matchers).

What is missing here is `buildContext()` copying the matchers from the parent ignore context, I think? I'm not a go developer, but I _think_ the code should be updated to read:

```go
	newic := &ignoreContext{
		parent:         d.parentContext,
		onIgnore:       d.parentContext.onIgnore,
		dotIgnoreFiles: effectiveDotIgnoreFiles,
		matchers:     	make([]wcmatch.WildcardMatcher, len(d.parentContext.matchers)),
		maxFileSize:    d.parentContext.maxFileSize,
		oneFileSystem:  d.parentContext.oneFileSystem,
	}

	copy(newic.matchers, d.parentContext.matchers)
```

This creates an empty slice with the same length as the parent context matchers slice, then copies the matchers across (the `make()` call is needed to allocate the right number of elements in the new `matchers` slice).

**Comment by mjpieters** [comment]
My analysis is not entirely correct, it seems. The [`shouldIncludeByName()` function](https://github.com/kopia/kopia/blob/e0e7f66a90e6c25120fb3dcd4db1df223041147e/fs/ignorefs/ignorefs.go#L35-L61) does the actual checking of a path against the matchers. It starts with:

```go
	// Start by checking with any ignores defined in a parent directory (if there is one).
	// Any matches here may be negated by .ignore-files in lower directories.
	if c.parent != nil {
		shouldIgnore = !c.parent.shouldIncludeByName(path, e)
	}
```

which implies the parent context is used. What confuses me here then is two things:

- Why does `overrideFromPolicy()` set `matchers` to `nil` if `NoParentIgnoreRules` is set? `matchers` is _always_ `nil`.
- Why doesn't `shouldIncludeByName()` consult `NoParentIgnoreRules` when it checks against the parent policy?
```

**Comment by sonalvrioss-svyatos** [comment]
Is this issue being addressed? I have to copy the global ignore rules to the snapshot ignore rules then add additional ignore rules for it to work.

**Comment by BradyRosino** [comment]
I know this is not a priority currently, which is absolutely fine... but I'm hoping this might be reopened? This is the only reason why I'm not currently using Kopia. If this is an intentional design choice, that is perfectly fine and my use case might not be the same as others. In that case it can stay closed.

However if this is only closed due to inactivity, please reconsider 😀

**Comment by mjpieters** [comment]
I very much doubt that this issue should have been closed. There is definitely confusion surrounding the feature and it looks broken to me.

**Comment by m-primo** [comment]
Why this issue has been closed with no solution?!
